# Generated by Django 2.1.2 on 2019-02-07 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='s_21_ActualDeliveryTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Actual Delivery Timestamp'),
        ),
    ]
