# Generated by Django 2.1.2 on 2019-02-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookings_s_21_actualdeliverytimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_urls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'dme_urls',
            },
        ),
    ]
