# Generated by Django 2.1.2 on 2019-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookings_vx_fp_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_manifest_url',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Manifest URL'),
        ),
    ]
