# Generated by Django 2.1.2 on 2019-02-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookings_z_manifest_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DME_Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=32, verbose_name='Role Code')),
                ('description', models.CharField(max_length=255, verbose_name='Role Description')),
            ],
            options={
                'db_table': 'dme_roles',
            },
        ),
    ]
