# Generated by Django 2.1.2 on 2019-02-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dme_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_employees',
            name='Role',
        ),
        migrations.AddField(
            model_name='dme_employees',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.DME_Roles'),
        ),
        migrations.AddField(
            model_name='dme_employees',
            name='warehouse_id',
            field=models.IntegerField(default=1, null=True, verbose_name='Warehouse ID'),
        ),
    ]
