# Generated by Django 2.1.2 on 2019-02-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190213_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dme_employees',
            old_name='role_id',
            new_name='role',
        ),
    ]
