# Generated by Django 2.1.2 on 2019-02-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190213_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_employees',
            name='fk_id_client_warehouses',
        ),
        migrations.AddField(
            model_name='client_employees',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.DME_Roles'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='warehouse_id',
            field=models.IntegerField(default=1, null=True, verbose_name='Warehouse ID'),
        ),
    ]
