# Generated by Django 2.1.2 on 2019-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190213_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_employees',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='client_employees',
            name='name_first',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client_employees',
            name='name_last',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client_employees',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='client_employees',
            name='warehouse_id',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Warehouse ID'),
        ),
    ]
