# Generated by Django 2.1.2 on 2019-02-17 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190213_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_attachments',
            fields=[
                ('pk_id_attachment', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=230, verbose_name='filename')),
                ('linkurl', models.CharField(blank=True, max_length=430, null=True, verbose_name='linkurl')),
                ('upload_Date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Upload Datatime')),
                ('fk_id_dme_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bookings')),
                ('fk_id_dme_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DME_clients')),
            ],
            options={
                'db_table': 'dme_attachments',
            },
        ),
    ]
