# Generated by Django 2.1.2 on 2019-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190222_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bok_1_headers',
            name='b_053_b_del_address_street',
        ),
    ]
