# Generated by Django 2.1.2 on 2019-02-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_bok_1_headers_b_053_b_del_address_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='deToAddressPostalCode',
        ),
    ]
