# Generated by Django 2.1.2 on 2019-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_bookings_detoaddresspostalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok_1_headers',
            name='z_test',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Test for b_client_booking_ref_num'),
        ),
    ]
