# Generated by Django 2.1.2 on 2019-02-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bok_1_headers_z_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bok_1_headers',
            name='b_client_booking_ref_num',
        ),
    ]
