# Generated by Django 2.1.2 on 2019-02-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190224_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bok_1_headers',
            name='b_client_booking_ref_num',
        ),
    ]
