# Generated by Django 2.1.2 on 2019-02-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bok_1_headers_b_client_booking_refnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bok_1_headers',
            old_name='b_client_booking_refnum',
            new_name='z_test',
        ),
    ]
