# Generated by Django 2.1.2 on 2019-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190224_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_pod_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
