# Generated by Django 2.1.2 on 2019-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_bookings_z_pod_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_lines',
            name='client_item_reference',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
