# Generated by Django 2.1.2 on 2019-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190227_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='total_lines_qty_override',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total Lines Qty Override'),
        ),
    ]
