# Generated by Django 2.1.2 on 2019-03-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_dme_log_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='z_temp_success_seaway_history',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Passed by log script'),
        ),
    ]
