# Generated by Django 2.1.2 on 2019-03-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_log_z_temp_success_seaway_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='vx_FP_ETA_Date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='vx_FP_ETA_Time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_fp_del_eta_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='FP Delivery ETA Time'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='vx_fp_pu_eta_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='FP PickUp ETA Time'),
        ),
    ]
