# Generated by Django 2.1.2 on 2019-03-06 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20190305_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_api_send_TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_api_start_TimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_api_try_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
