# Generated by Django 2.1.2 on 2019-03-06 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190306_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_downloaded_pod_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
