# Generated by Django 2.1.2 on 2019-03-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_bookings_z_downloaded_pod_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='z_downloaded_pod_timestamp',
        ),
    ]
