# Generated by Django 2.1.2 on 2019-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_bookings_z_downloaded_pod_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_downloaded_pod_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
