# Generated by Django 2.1.2 on 2019-03-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_bookings_z_downloaded_pod_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_api_send_TimeStamp',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='booking_api_start_TimeStamp',
        ),
    ]
