# Generated by Django 2.1.2 on 2019-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190306_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_api_end_TimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_api_start_TimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
