# Generated by Django 2.1.2 on 2019-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190307_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_api_try_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
