# Generated by Django 2.1.2 on 2019-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190308_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_dateBookedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booked Date'),
        ),
    ]
