# Generated by Django 2.1.2 on 2019-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190310_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_client_Reference_RA_Numbers_lastupdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Client Reference RA Number Last Update'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_date_booked_by_dme',
            field=models.DateField(blank=True, null=True, verbose_name='Date Booked By DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='b_dateinvoice',
            field=models.DateField(blank=True, null=True, verbose_name='Date Invoice'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_Deliver_By_Date',
            field=models.DateField(blank=True, null=True, verbose_name='DE By Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_Deliver_From_Date',
            field=models.DateField(blank=True, null=True, verbose_name='DE From Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_TimeSlot_TimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='DE TimeSlot TimeStart'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_TimeSlot_Time_End',
            field=models.TimeField(blank=True, null=True, verbose_name='TimeSlot Time End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='de_to_TimeSlot_Date_End',
            field=models.DateField(blank=True, null=True, verbose_name='DE to TimeSlot Date End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='puPickUpAvailFrom_Date',
            field=models.DateField(blank=True, null=True, verbose_name='PickUp Available From'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Actual_Date',
            field=models.DateField(blank=True, null=True, verbose_name='PU Actual Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Actual_PickUp_Time',
            field=models.TimeField(blank=True, null=True, verbose_name='Actual PU Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_Avail_From_Date_DME',
            field=models.DateField(blank=True, null=True, verbose_name='PU Available From Date DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_By_Date',
            field=models.DateField(blank=True, null=True, verbose_name='PickUp By Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_By_Date_DME',
            field=models.DateField(blank=True, null=True, verbose_name='PU By Date DME'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_PickUp_TimeSlot_TimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='PU TimeSlot TimeEnd'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_02_Booking_Cutoff_Time',
            field=models.TimeField(blank=True, null=True, verbose_name='Booking Cutoff Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_05_LatestPickUpDateTimeFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lastest PickUp DateTime'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_05_Latest_PickUp_Date_Time_Override',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest PU DateTime Override'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_05_Latest_Pick_Up_Date_TimeSet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest PU DateTime Set'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_06_LatestDeliveryDateTimeFinal',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest Delivery DateTime'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_06_Latest_Delivery_Date_TimeSet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest DE DateTime Set'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_06_Latest_Delivery_Date_Time_Override',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Latest DE DateTime Override'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_20_Actual_Pickup_TimeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual PU TimeStamp'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_21_ActualDeliveryTimeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Timestamp'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='s_21_Actual_Delivery_TimeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual DE TimeStamp'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='v_serviceTime_End',
            field=models.TimeField(blank=True, null=True, verbose_name='Service Time End'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='v_serviceTime_Start',
            field=models.TimeField(blank=True, null=True, verbose_name='Service Time Start'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_fp_del_eta_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FP Delivery ETA Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_fp_pu_eta_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FP PickUp ETA Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vx_freight_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Freight Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='z_CreatedTimestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created By Account'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='z_ModifiedTimestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modified By Account'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='z_downloaded_shipping_label_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='downloaded_shipping_label_timestamp'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='z_included_with_manifest_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Included With Manifest Date'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='z_lastStatusAPI_ProcessedTimeStamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last StatusAPI Processed Timestamp'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
