# Generated by Django 2.1.2 on 2019-03-11 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190310_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_comm_and_task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Booking ID')),
                ('assigned_to', models.CharField(blank=True, max_length=64, null=True, verbose_name='Assigned To')),
                ('priority_of_log', models.FloatField(blank=True, null=True, verbose_name='Priority Of Log')),
                ('dme_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='DME Action')),
                ('dme_notes_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='DME Notes Type')),
                ('dme_notes', models.TextField(blank=True, max_length=4096, null=True, verbose_name='DME Notes')),
                ('dme_notes_external', models.TextField(blank=True, max_length=4096, null=True, verbose_name='DME Notes External')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Status')),
                ('query', models.CharField(blank=True, max_length=254, null=True, verbose_name='Query')),
                ('due_by_date', models.DateField(blank=True, null=True, verbose_name='Due By Date')),
                ('due_by_time', models.TimeField(blank=True, null=True, verbose_name='Due By Time')),
                ('due_by_new_date', models.DateField(blank=True, null=True, verbose_name='Due By New Date')),
                ('due_by_new_time', models.TimeField(blank=True, null=True, verbose_name='Due By New Time')),
                ('final_due_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Final Due Date Time')),
                ('status_log_closed_time', models.DateTimeField(blank=True, null=True, verbose_name='Status Log Closed Time')),
                ('z_snooze_option', models.FloatField(blank=True, null=True, verbose_name='Snooze Option')),
                ('z_time_till_due_sec', models.FloatField(blank=True, null=True, verbose_name='Time Till Due Second')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_comm_and_task',
            },
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
