# Generated by Django 2.1.2 on 2019-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190311_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_comm_and_task',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Closed'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
