# Generated by Django 2.1.2 on 2019-03-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190311_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_comm_and_task',
            name='priority_of_log',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Priority Of Log'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
