# Generated by Django 2.1.2 on 2019-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20190312_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_comm_and_task',
            name='dme_notes',
        ),
        migrations.AddField(
            model_name='dme_comm_and_task',
            name='dme_com_title',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='DME Comm Title'),
        ),
        migrations.AlterField(
            model_name='dme_comm_and_task',
            name='dme_notes_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DME Detail'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
