# Generated by Django 2.1.2 on 2019-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190312_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dme_comm_and_task',
            old_name='dme_notes_type',
            new_name='dme_detail',
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
