# Generated by Django 2.1.2 on 2019-03-12 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190312_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_comm_notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='User')),
                ('dme_notes', models.TextField(blank=True, max_length=4096, null=True, verbose_name='DME Notes')),
                ('dme_notes_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='DME Notes Type')),
                ('dme_notes_no', models.IntegerField(default=1, verbose_name='DME Notes No')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
                ('comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dme_comm_and_task')),
            ],
            options={
                'db_table': 'dme_comm_notes',
            },
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
