# Generated by Django 2.1.2 on 2019-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190312_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_comm_and_task',
            name='dme_notes_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='DME Notes Type'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
