# Generated by Django 2.1.2 on 2019-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20190313_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='b_status_API',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Status API'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
