# Generated by Django 2.1.2 on 2019-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190318_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_comm_notes',
            name='note_time_created',
            field=models.TimeField(blank=True, null=True, verbose_name='Time First'),
        ),
        migrations.AddField(
            model_name='dme_comm_notes',
            name='note_time_updated',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Modified'),
        ),
        migrations.AlterField(
            model_name='dme_comm_notes',
            name='note_date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date First'),
        ),
        migrations.AlterField(
            model_name='dme_comm_notes',
            name='note_date_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Date Modified'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
