# Generated by Django 2.1.2 on 2019-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20190318_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_comm_and_task',
            name='dme_action',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='DME Action'),
        ),
        migrations.AlterField(
            model_name='dme_comm_and_task',
            name='dme_com_title',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='DME Comm Title'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
