# Generated by Django 2.1.2 on 2019-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190405_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='de_To_Address_Suburb',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='DE Address Suburb'),
        ),
        # migrations.AlterField(
        #     model_name='utl_states',
        #     name='fk_country_id',
        #     field=models.CharField(blank=True, default='', max_length=32, null=True),
        # ),
    ]
