# Generated by Django 2.1.2 on 2019-04-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190405_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_lines',
            name='total_2_cubic_mass_factor_calc',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cubic Mass Factor'),
        ),
    ]
