# Generated by Django 2.1.2 on 2019-04-08 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190406_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_package_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dmePackageTypeCode', models.CharField(blank=True, max_length=25, null=True, verbose_name='DME Package Type Code')),
                ('dmePackageCategory', models.CharField(blank=True, max_length=25, null=True, verbose_name='DME Package Category')),
                ('dmePackageTypeDesc', models.CharField(blank=True, max_length=50, null=True, verbose_name='DME Package Type Desc')),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_package_types',
            },
        ),
    ]
