# Generated by Django 2.1.2 on 2019-04-09 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190408_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_employees',
            name='clien_emp_job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='clientEmployeeCommLateBookings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='clientEmployeeEmail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='clientEmployeeSalutation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='clientEmployeeSpecialInstruc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_address_suburb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_name_frst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_name_surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_phone_fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_phone_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='client_emp_phone_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='z_createdByAccount',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Created By Account'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='z_createdTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Created Timestamp'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='z_modifiedByAccount',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Modified By Account'),
        ),
        migrations.AddField(
            model_name='client_employees',
            name='z_modifiedTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Modified Timestamp'),
        ),
    ]
