# Generated by Django 2.1.2 on 2019-04-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190409_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_manual_booking_set_time_push_to_fm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_manual_booking_set_to_confirm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
