# Generated by Django 2.1.2 on 2019-04-19 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190410_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_status_history',
            name='depot_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Depot Name'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='event_time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Event Timestamp'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='fk_fp_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='FP ID'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='status_code_api',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Status Code API'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='status_from_api',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Status From API'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='updateViaAPI',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Updated via API'),
        ),
        migrations.DeleteModel(
            name='Booking_Status_History',
        ),
    ]
