# Generated by Django 2.1.2 on 2019-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190419_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='z_lock_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_locked_status_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
