# Generated by Django 2.1.2 on 2019-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190420_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_status_history',
            name='api_status_time_stamp',
        ),
        migrations.RemoveField(
            model_name='dme_status_history',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='dme_status_history',
            name='updateViaAPI',
        ),
        migrations.RemoveField(
            model_name='dme_status_history',
            name='update_via_api',
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Recipient Name'),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='status_update_via',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Status Updated Via'),
        ),
    ]
