# Generated by Django 2.1.2 on 2019-04-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20190424_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='utl_dme_status',
            name='sort_order',
            field=models.IntegerField(default=1, verbose_name='phone number'),
        ),
    ]
