# Generated by Django 2.1.2 on 2019-04-29 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20190428_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_utl_fp_statuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_status', models.CharField(blank=True, max_length=150, null=True)),
                ('fk_fp_id', models.IntegerField(blank=True, default=1, null=True)),
                ('fp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fp_original_status', models.TextField(blank=True, max_length=400, null=True)),
                ('fp_lookup_status', models.TextField(blank=True, max_length=400, null=True)),
                ('dme_status', models.CharField(blank=True, max_length=150, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_utl_fp_statuses',
            },
        ),
    ]
