# Generated by Django 2.1.2 on 2019-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20190429_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_utl_fp_statuses',
            name='fp_status',
        ),
    ]
