# Generated by Django 2.1.2 on 2019-05-01 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20190429_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utl_fp_delivery_times',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_fp_id', models.IntegerField(blank=True, default=1, null=True)),
                ('fp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code_from', models.IntegerField(blank=True, default=1, null=True)),
                ('postal_code_to', models.IntegerField(blank=True, default=1, null=True)),
                ('delivery_days', models.FloatField(blank=True, default=7, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'utl_fp_delivery_times',
            },
        ),
    ]
