# Generated by Django 2.1.2 on 2019-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20190501_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='delivery_actual_kpi_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='delivery_days_from_booked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='delivery_kpi_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_api_try_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
