# Generated by Django 2.1.2 on 2019-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20190501_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='b_status_sub',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
