# Generated by Django 2.1.2 on 2019-05-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20190505_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_adjusted_delivered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_awaiting_inventory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_damaged',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_delivered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_returned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_scanned_depot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_shortages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
