# Generated by Django 2.1.2 on 2019-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20190505_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='b_status_sub',
            new_name='b_status_sub_client',
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_status_sub_fp',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
