# Generated by Django 2.1.2 on 2019-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190506_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='store_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='store_booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
