# Generated by Django 2.1.2 on 2019-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20190507_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_booking_confirmation_lines',
            name='client_item_reference',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='api_booking_confirmation_lines',
            name='label_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
