# Generated by Django 2.1.2 on 2019-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20190509_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_booking_confirmation_lines',
            name='tally',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='e_qty_scanned_fp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='e_qty_scanned_fp_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
