# Generated by Django 2.1.2 on 2019-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20190509_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='store_booking_date',
            new_name='fp_store_event_date',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='store_booking_time',
            new_name='fp_store_event_time',
        ),
    ]
