# Generated by Django 2.1.2 on 2019-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20190509_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utl_dme_status',
            name='sort_order',
            field=models.FloatField(default=1, verbose_name='sort order'),
        ),
    ]
