# Generated by Django 2.1.2 on 2019-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20190512_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='utl_dme_status',
            name='z_show_client_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
