# Generated by Django 2.1.2 on 2019-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20190512_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dme_status_action',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='dme_status_linked_reference_from_fp',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='dme_status_reason',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
