# Generated by Django 2.1.2 on 2019-05-14 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20190514_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fp_freight_providers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('fp_address_country', models.CharField(blank=True, max_length=32, null=True)),
                ('fp_inactive_date', models.DateField(blank=True, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'fp_freight_providers',
            },
        ),
    ]
