# Generated by Django 2.1.2 on 2019-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20190514_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='dme_status_reason',
            new_name='dme_status_details',
        ),
    ]
