# Generated by Django 2.1.2 on 2019-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20190515_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_status_history',
            name='dme_status_action',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='dme_status_details',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='dme_status_linked_reference_from_fp',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
