# Generated by Django 2.1.2 on 2019-05-15 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20190515_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utl_dme_status_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dme_status_details', models.CharField(blank=True, max_length=64, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'utl_dme_status_details',
            },
        ),
        migrations.CreateModel(
            name='Utl_dme_status_reasons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dme_status_reasons', models.CharField(blank=True, max_length=64, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'utl_dme_status_reasons',
            },
        ),
    ]
