# Generated by Django 2.1.2 on 2019-05-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20190515_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_status_history',
            name='b_booking_visualID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='b_status_api',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dme_status_history',
            name='total_scanned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dme_utl_fp_statuses',
            name='if_scan_total_in_booking_greaterthanzero',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
