# Generated by Django 2.1.2 on 2019-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20190520_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermissions',
            table='user_permissions',
        ),
    ]
