# Generated by Django 2.1.2 on 2019-05-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20190520_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dev_notes',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
