# Generated by Django 2.1.2 on 2019-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20190521_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_utl_fp_statuses',
            name='pod_delivery_override',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
