# Generated by Django 2.1.2 on 2019-06-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20190531_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='dme_status_history_notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='dme_status_action',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='dme_status_detail',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
