# Generated by Django 2.1.2 on 2019-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20190601_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dme_status_history_notes',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
