# Generated by Django 2.1.2 on 2019-06-11 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20190606_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dme_maifest_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='FK Booking Id')),
                ('manifest_url', models.CharField(blank=True, max_length=200, null=True)),
                ('z_createdByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Created by account')),
                ('z_createdTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Timestamp')),
                ('z_modifiedByAccount', models.CharField(blank=True, max_length=64, null=True, verbose_name='Modified by account')),
                ('z_modifiedTimeStamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Timestamp')),
            ],
            options={
                'db_table': 'dme_maifest_log',
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='manifest_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
