# Generated by Django 2.1.2 on 2019-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20190611_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dme_maifest_log',
            new_name='Dme_manifest_log',
        ),
    ]
