# Generated by Django 2.1.2 on 2019-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20190611_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_freight_providers',
            name='fp_manifest_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
