# Generated by Django 2.1.2 on 2019-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20190617_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_freight_providers',
            name='new_connot_index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fp_freight_providers',
            name='fp_manifest_cnt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
