# Generated by Django 2.1.2 on 2019-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20190620_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_clients',
            name='current_freight_provider',
            field=models.CharField(default='*', max_length=30, null=True, verbose_name='Related FP'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Address_Street_1',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='PU Address Street 1'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pu_Address_street_2',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='PU Address Street 2'),
        ),
        migrations.AlterField(
            model_name='dme_clients',
            name='company_name',
            field=models.CharField(max_length=128, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='dme_clients',
            name='dme_account_num',
            field=models.CharField(default='', max_length=64, verbose_name='dme account num'),
        ),
    ]
