# Generated by Django 2.1.2 on 2019-07-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0106_auto_20190626_1742")]

    operations = [
        # migrations.AddField(
        #     model_name='bookings',
        #     name='z_connote_url',
        #     field=models.CharField(blank=True, default='', max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='bookings',
        #     name='z_downloaded_connote_timestamp',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
    ]
