# Generated by Django 2.1.2 on 2019-07-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0108_auto_20190710_0735")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="z_first_scan_label_date",
            field=models.DateField(blank=True, null=True),
        )
    ]
