# Generated by Django 2.1.2 on 2019-07-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0109_auto_20190716_0519")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="check_pod",
            field=models.BooleanField(blank=True, default=False, null=True),
        )
    ]
