# Generated by Django 2.1.2 on 2019-07-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0110_auto_20190720_0234")]

    operations = [
        migrations.AlterField(
            model_name="dme_attachments",
            name="fk_id_dme_booking",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="FK Booking Id"
            ),
        )
    ]
