# Generated by Django 2.1.2 on 2019-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0112_auto_20190727_2005")]

    operations = [
        migrations.CreateModel(
            name="DHL_fp_zones",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("suburb", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=16, null=True)),
                ("zone", models.CharField(blank=True, max_length=50, null=True)),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                ("service", models.CharField(blank=True, max_length=50, null=True)),
                ("sender_code", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"db_table": "dhl_fp_zones"},
        )
    ]
