# Generated by Django 2.1.2 on 2019-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0113_auto_20190802_0811")]

    operations = [migrations.RenameModel(old_name="DHL_fp_zones", new_name="FP_zones")]
