# Generated by Django 2.1.2 on 2019-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0114_auto_20190802_1539")]

    operations = [
        migrations.AlterModelTable(name="fp_zones", table="fp_zones"),
        migrations.AddField(
            model_name="fp_zones",
            name="fk_fp",
            field=models.CharField(max_length=32, blank=True, null=True, default=None),
        ),
    ]
