# Generated by Django 2.1.2 on 2019-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0116_auto_20190802_1548")]

    operations = [
        migrations.CreateModel(
            name="FP_carriers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fk_fp",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "start_value",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("end_value", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "current_value",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={"db_table": "fp_carriers"},
        )
    ]
