# Generated by Django 2.1.2 on 2019-08-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0118_auto_20190803_1851")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="fk_manifest",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Dme_manifest_log",
            ),
        )
    ]
