# Generated by Django 2.1.2 on 2019-08-12 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0119_auto_20190806_2215")]

    operations = [
        migrations.CreateModel(
            name="FP_label_scans",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fk_fp",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "label_code",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "client_item_reference",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("scanned_date", models.DateField(blank=True, default=None, null=True)),
                ("scanned_time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "scanned_by",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
            ],
        )
    ]
