# Generated by Django 2.1.2 on 2019-08-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0120_auto_20190812_0210")]

    operations = [
        migrations.AlterModelTable(name="fp_label_scans", table="fp_label_scans")
    ]
