# Generated by Django 2.1.2 on 2019-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0121_auto_20190812_0222")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_is_flagged_add_on_services",
            field=models.BooleanField(blank=True, default=False, null=True),
        )
    ]
