# Generated by Django 2.1.2 on 2019-08-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0122_auto_20190813_0705")]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_000_3_consignment_nuumber",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                null=True,
                verbose_name="FP Booking Number",
            ),
        )
    ]
