# Generated by Django 2.1.2 on 2019-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0124_auto_20190814_1039")]

    operations = [
        migrations.AddField(
            model_name="client_warehouses",
            name="success_type",
            field=models.IntegerField(default=0),
        )
    ]
