# Generated by Django 2.1.2 on 2019-08-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0125_auto_20190819_2358")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="deToCompanyName",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                null=True,
                verbose_name="Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="puCompany",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                null=True,
                verbose_name="Company",
            ),
        ),
    ]
