# Generated by Django 2.1.2 on 2019-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0126_auto_20190822_1508")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="z_calculated_ETA",
            field=models.DateField(blank=True, null=True),
        )
    ]
