# Generated by Django 2.1.2 on 2019-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0127_auto_20190829_0849")]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="kf_Invoice_Num_Booking",
            new_name="inv_dme_invoice_no",
        ),
        migrations.AddField(
            model_name="bookings",
            name="b_client_name_sub",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="fp_invoice_no",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="inv_cost_actual",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="inv_cost_quoted",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="inv_sell_actual",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="inv_sell_quoted",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_calculated_ETA",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
