# Generated by Django 2.1.2 on 2019-09-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0128_auto_20190830_0624")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="z_calculated_ETA",
            field=models.DateField(blank=True, null=True),
        )
    ]
