# Generated by Django 2.1.2 on 2019-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0129_auto_20190901_2234")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="inv_cost_actual",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_cost_quoted",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_sell_actual",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_sell_quoted",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
