# Generated by Django 2.1.2 on 2019-09-04 01:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0130_auto_20190903_0033"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_reports",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("type", models.CharField(blank=True, max_length=32, null=True)),
                ("url", models.TextField(blank=True, max_length=512, null=True)),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_downloadedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Downloaded by account",
                    ),
                ),
                (
                    "z_downloadedTimeStamp",
                    models.DateTimeField(
                        default=None, verbose_name="Downloaded Timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "dme_reports"},
        )
    ]
