# Generated by Django 2.1.2 on 2019-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0131_auto_20190905_0712")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_del_to_signed_name",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="b_del_to_signed_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
