# Generated by Django 2.1.2 on 2019-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0132_auto_20190915_2342")]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="z_pushed_to_fm",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="booking_lines_data",
            name="z_pushed_to_fm",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="z_pushed_to_fm",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
