# Generated by Django 2.1.2 on 2019-09-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20190904_0113'),
        ('api', '0133_auto_20190919_0922'),
    ]

    operations = [
    ]
