# Generated by Django 2.1.2 on 2019-10-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0134_merge_20190921_1639")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_fp_qty_delivered",
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
