# Generated by Django 2.1.2 on 2019-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0136_auto_20191015_0525")]

    operations = [
        migrations.AlterField(
            model_name="booking_lines",
            name="e_weightPerEach",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Weight Per Each"
            ),
        )
    ]
