# Generated by Django 2.1.2 on 2019-10-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0138_auto_20191017_2243")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_booking_project",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        )
    ]
