# Generated by Django 2.1.2 on 2019-10-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0138_auto_20191017_2243")]

    operations = [
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="api_results_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Result ID"
            ),
        )
    ]
