# Generated by Django 2.1.2 on 2019-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0139_auto_20191019_0201")]

    operations = [
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="tax_value_1",
            field=models.FloatField(blank=True, null=True, verbose_name="Tax Value 1"),
        ),
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="tax_value_2",
            field=models.FloatField(blank=True, null=True, verbose_name="Tax Value 2"),
        ),
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="tax_value_3",
            field=models.FloatField(blank=True, null=True, verbose_name="Tax Value 3"),
        ),
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="tax_value_4",
            field=models.FloatField(blank=True, null=True, verbose_name="Tax Value 4"),
        ),
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="tax_value_5",
            field=models.FloatField(blank=True, null=True, verbose_name="Tax Value 5"),
        ),
    ]
