# Generated by Django 2.1.2 on 2019-10-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0140_auto_20191019_0354")]

    operations = [
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="service_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Service Name"
            ),
        )
    ]
