# Generated by Django 2.1.2 on 2019-11-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20191028_0734'),
        ('api', '0141_auto_20191031_1102'),
        ('api', '0144_auto_20191030_0044'),
    ]

    operations = [
    ]
