# Generated by Django 2.1.2 on 2019-11-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0145_merge_20191103_2103")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="de_Email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="DE Email",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="PU Email",
            ),
        ),
    ]
