# Generated by Django 2.1.2 on 2019-11-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0146_auto_20191103_2103")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="project_due_date",
            field=models.DateField(blank=True, default=None, null=True),
        )
    ]
