# Generated by Django 2.1.2 on 2019-11-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0147_auto_20191111_2354")]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="project_due_date",
            new_name="b_project_due_date",
        )
    ]
