# Generated by Django 2.1.2 on 2019-11-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0148_auto_20191112_0031")]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="fp_received_date_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="fp_warehouse_collected_date_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
