# Generated by Django 2.1.2 on 2019-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0151_auto_20191116_0852")]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="fp_received_date_time",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
