# Generated by Django 2.1.2 on 2019-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0152_auto_20191120_0807")]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="fp_warehouse_collected_date_time",
            new_name="b_given_to_transport_date_time",
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_connote_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='z_downloaded_connote_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dme_reports',
            name='z_downloadedTimeStamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Downloaded Timestamp'),
        ),
        migrations.AlterField(
            model_name='utl_states',
            name='fk_country_id',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
