# Generated by Django 2.1.2 on 2019-11-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0153_auto_20191124_2304")]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="api_booking_quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        )
    ]
