# Generated by Django 2.1.2 on 2019-11-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0154_auto_20191125_0849")]

    operations = [
        migrations.RemoveField(model_name="booking_lines", name="api_booking_quote"),
        migrations.AddField(
            model_name="bookings",
            name="api_booking_quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
    ]
