# Generated by Django 2.1.2 on 2019-12-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0157_auto_20191218_2350")]

    operations = [
        # migrations.RenameField(
        #     model_name="booking_lines_data",
        #     old_name="fk_id_booking_lines",
        #     new_name="fk_booking_lines_id",
        # ),
        # migrations.RemoveField(model_name="bok_3_lines_data", name="fk_booking_id"),
        # migrations.AddField(
        #     model_name="bok_2_lines",
        #     name="pk_booking_lines_id",
        #     field=models.CharField(
        #         blank=True, max_length=64, null=True, verbose_name="PK Booking Line"
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="bok_3_lines_data",
        #     name="fk_booking_lines_id",
        #     field=models.CharField(
        #         blank=True, max_length=64, null=True, verbose_name="FK Booking Lines Id"
        #     ),
        # ),
        migrations.AddField(
            model_name="booking_lines",
            name="pk_booking_lines_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="PK Booking Line"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_Category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="Booking Categroy",
            ),
        ),
        # migrations.RemoveField(
        #     model_name="booking_lines_data", name="fk_id_booking_lines"
        # ),
        # migrations.AddField(
        #     model_name="booking_lines",
        #     name="pk_booking_lines_id",
        #     field=models.CharField(blank=True, max_length=64, null=True),
        # ),
        # migrations.AddField(
        #     model_name="booking_lines_data",
        #     name="fk_booking_lines_id",
        #     field=models.CharField(
        #         blank=True, max_length=64, null=True, verbose_name="FK Booking Lines Id"
        #     ),
        # ),
    ]
