# Generated by Django 2.1.2 on 2019-12-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0158_auto_20191219_2351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_020_b_pu_num_operators",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="b_020_b_pu_num_operators",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_042_b_del_num_operators",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="b_042_b_del_num_operators",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_bookingNoOperatorDeliver",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Booking No Operator DE",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_no_operator_pickup",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Booking No Operator PU",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="x_ReadyStatus",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                null=True,
                verbose_name="Ready Status",
            ),
        ),
    ]
