# Generated by Django 2.1.2 on 2020-01-08 01:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0159_auto_20191230_1424"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_Options",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("option_name", models.CharField(blank=True, max_length=255)),
                ("option_value", models.CharField(blank=True, max_length=8)),
                ("option_description", models.TextField(blank=True, max_length=1024)),
                (
                    "option_schedule",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("end_time", models.DateTimeField(blank=True, default=None, null=True)),
                ("start_count", models.IntegerField(blank=True, default=0, null=True)),
                ("end_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "elapsed_seconds",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "is_running",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_downloadedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_downloadedTimeStamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Modified Timestamp",
                    ),
                ),
            ],
            options={"db_table": "dme_options",},
        ),
        migrations.RenameField(
            model_name="booking_lines_data",
            old_name="fk_id_booking_lines",
            new_name="fk_booking_lines_id",
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_021_b_pu_avail_from_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, verbose_name="Available From"
            ),
        ),
    ]
