# Generated by Django 2.1.2 on 2020-01-11 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0160_auto_20200108_0127"),
    ]

    operations = [
        migrations.CreateModel(
            name="FP_Store_Booking_Log",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "v_FPBookingNumber",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "fp_store_scheduled_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "fp_store_event_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "fp_store_event_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
            ],
            options={"db_table": "fp_store_booking_log",},
        ),
        migrations.AddField(
            model_name="bookings",
            name="fp_store_scheduled_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_024_b_pu_by_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
