# Generated by Django 2.1.2 on 2020-01-12 06:37
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0161_auto_20200111_0805"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="fp_store_scheduled_date",
            new_name="delivery_booking",
        ),
        migrations.AddField(
            model_name="fp_store_booking_log",
            name="csv_file_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_047_b_del_avail_from_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_050_b_del_by_date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
