# Generated by Django 2.1.2 on 2020-01-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0163_auto_20200112_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="fp_store_event_desc",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
