# Generated by Django 2.1.2 on 2020-01-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0164_auto_20200122_0642"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_store_booking_log",
            name="fp_store_event_desc",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
