# Generated by Django 2.1.2 on 2020-02-06 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0165_auto_20200122_0655"),
    ]

    operations = [
        migrations.CreateModel(
            name="FP_availabilities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("mon_start", models.TimeField(blank=True, default=None, null=True)),
                ("mon_end", models.TimeField(blank=True, default=None, null=True)),
                ("tue_start", models.TimeField(blank=True, default=None, null=True)),
                ("tue_end", models.TimeField(blank=True, default=None, null=True)),
                ("wed_start", models.TimeField(blank=True, default=None, null=True)),
                ("wed_end", models.TimeField(blank=True, default=None, null=True)),
                ("thu_start", models.TimeField(blank=True, default=None, null=True)),
                ("thu_end", models.TimeField(blank=True, default=None, null=True)),
                ("fri_start", models.TimeField(blank=True, default=None, null=True)),
                ("fri_end", models.TimeField(blank=True, default=None, null=True)),
                ("sat_start", models.TimeField(blank=True, default=None, null=True)),
                ("sat_end", models.TimeField(blank=True, default=None, null=True)),
                ("sun_start", models.TimeField(blank=True, default=None, null=True)),
                ("sun_end", models.TimeField(blank=True, default=None, null=True)),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={"db_table": "fp_availabilities",},
        ),
        migrations.CreateModel(
            name="FP_costs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "UOM_charge",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("start_qty", models.IntegerField(blank=True, default=0, null=True)),
                ("end_qty", models.IntegerField(blank=True, default=0, null=True)),
                ("basic_charge", models.FloatField(blank=True, default=0, null=True)),
                ("min_charge", models.FloatField(blank=True, default=0, null=True)),
                ("per_UOM_charge", models.FloatField(blank=True, default=0, null=True)),
                (
                    "oversize_premium",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("oversize_pice", models.FloatField(blank=True, default=0, null=True)),
                (
                    "m3_to_kg_factor",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "dim_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "price_up_to_length",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "price_up_to_width",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "price_up_to_heigth",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "weight_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "price_up_to_weight",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("max_length", models.FloatField(blank=True, default=0, null=True)),
                ("max_width", models.FloatField(blank=True, default=0, null=True)),
                ("max_height", models.FloatField(blank=True, default=0, null=True)),
                ("max_weight", models.FloatField(blank=True, default=0, null=True)),
            ],
            options={"db_table": "fp_costs",},
        ),
        migrations.CreateModel(
            name="FP_pricing_rules",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "serivce_type",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "service_timing_code",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "calc_type",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "charge_rule",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.FP_costs"
                    ),
                ),
                (
                    "de_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="de_zone",
                        to="api.FP_zones",
                    ),
                ),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
                (
                    "pu_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pu_zone",
                        to="api.FP_zones",
                    ),
                ),
            ],
            options={"db_table": "fp_pricing_rules",},
        ),
        migrations.CreateModel(
            name="FP_timings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "time_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("min", models.IntegerField(blank=True, default=0, null=True)),
                ("max", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "booking_cut_off_time",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                ("collected_by", models.TimeField(blank=True, default=None, null=True)),
                ("delivered_by", models.TimeField(blank=True, default=None, null=True)),
            ],
            options={"db_table": "fp_timings",},
        ),
        migrations.CreateModel(
            name="FP_vehicles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "dim_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("max_length", models.FloatField(blank=True, default=0, null=True)),
                ("max_width", models.FloatField(blank=True, default=0, null=True)),
                ("max_height", models.FloatField(blank=True, default=0, null=True)),
                (
                    "mass_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                ("pallets", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "pallet_UOM",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "max_pallet_length",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "max_pallet_width",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                (
                    "max_pallet_height",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("base_charge", models.IntegerField(blank=True, default=0, null=True)),
                ("min_charge", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "limited_state",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={"db_table": "fp_vehicles",},
        ),
    ]
