# Generated by Django 2.1.2 on 2020-02-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0167_auto_20200206_0612"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fp_costs", old_name="oversize_pice", new_name="oversize_price",
        ),
    ]
