# Generated by Django 2.1.2 on 2020-02-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0168_auto_20200206_0747"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="de_postal_code",
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="de_state",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="de_suburb",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="pu_postal_code",
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="pu_state",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="pu_suburb",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="fp_pricing_rules",
            name="de_zone",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="fp_pricing_rules",
            name="pu_zone",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
