# Generated by Django 2.1.2 on 2020-02-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0170_auto_20200210_0300"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.FP_vehicles",
            ),
        ),
    ]
