# Generated by Django 2.1.2 on 2020-02-10 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0171_auto_20200210_0616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fp_pricing_rules",
            name="charge_rule",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
