# Generated by Django 2.1.2 on 2020-02-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_auto_20200111_0805'),
        ('api', '0173_auto_20200210_2312'),
    ]

    operations = [
    ]
