# Generated by Django 2.1.2 on 2020-02-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0174_merge_20200211_0106"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_000_0_b_client_agent_code",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_014_b_pu_handling_instructions",
            field=models.TextField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="b_014_b_pu_handling_instructions",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_015_b_pu_instructions_contact",
            field=models.TextField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="b_015_b_pu_instructions_contact",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_016_b_pu_instructions_address",
            field=models.TextField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="b_016_b_pu_instructions_address",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_043_b_del_instructions_contact",
            field=models.TextField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="b_043_b_del_instructions_contact",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_044_b_del_instructions_address",
            field=models.TextField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="b_044_b_del_instructions_address",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_handling_Instructions",
            field=models.TextField(
                blank=True,
                default="",
                max_length=120,
                null=True,
                verbose_name="Handling Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_PickUp_Instructions_Address",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="DE Instructions Address",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Pick_Up_Instructions_Contact",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="DE Instructions Contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_Instructions_Contact",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="PU Instructions Contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_pickup_instructions_address",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="Pickup instrunctions address",
            ),
        ),
    ]
