# Generated by Django 2.1.2 on 2020-02-12 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0175_auto_20200211_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_freight_providers",
            name="prices_count",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
