# Generated by Django 2.1.2 on 2020-02-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0176_auto_20200212_0219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fp_costs",
            old_name="price_up_to_heigth",
            new_name="price_up_to_height",
        ),
    ]
