# Generated by Django 2.1.2 on 2020-02-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0177_auto_20200214_0706"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_zones",
            name="end_postal_code",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="fp_zones",
            name="start_postal_code",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
