# Generated by Django 2.1.2 on 2020-02-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0179_auto_20200220_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_021_b_pu_avail_from_date",
            field=models.DateField(
                blank=True, default=None, verbose_name="Available From"
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_024_b_pu_by_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_047_b_del_avail_from_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_050_b_del_by_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
