# Generated by Django 2.1.2 on 2020-03-10 07:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0180_auto_20200221_1144"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_Files",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Role Code"),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime.now,
                        verbose_name="Created Timestamp",
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(max_length=32, verbose_name="Role Description"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=16, verbose_name="Role Description"),
                ),
                (
                    "file_extension",
                    models.CharField(max_length=8, verbose_name="Role Description"),
                ),
                (
                    "note",
                    models.TextField(max_length=512, verbose_name="Role Description"),
                ),
            ],
            options={"db_table": "dme_files",},
        ),
    ]
