# Generated by Django 2.1.2 on 2020-03-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0182_auto_20200312_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_036_b_pu_email_group",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_062_b_del_email_group",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Email_Group_Emails",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="DE Email Group Emails",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_email_Group",
            field=models.TextField(
                blank=True,
                default="",
                max_length=512,
                null=True,
                verbose_name="PU Email Group",
            ),
        ),
        migrations.AlterField(
            model_name="client_auto_augment",
            name="sales_club_de_Email_Group_Emails",
            field=models.TextField(
                blank=True,
                default="stock@salesclub.com.au, suraj@salesclub.com.au, Patrick@factoryseconds.biz, david@factoryseconds.biz",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client_auto_augment",
            name="tic_de_Email_Group_Emails",
            field=models.TextField(
                blank=True, default="rloqa@ticgroup.com.au", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_de_Email_Group_Emails",
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="dme_reports",
            name="z_downloadedTimeStamp",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Downloaded Timestamp"
            ),
        ),
    ]
