# Generated by Django 2.1.2 on 2020-03-13 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0182_auto_20200312_0623"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utl_sql_queries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sql_title",
                    models.CharField(
                        blank=True, max_length=36, null=True, verbose_name="SQL Title"
                    ),
                ),
                (
                    "sql_query",
                    models.TextField(blank=True, null=True, verbose_name="SQL Query"),
                ),
                (
                    "sql_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="SQL Description"
                    ),
                ),
                (
                    "sql_notes",
                    models.TextField(blank=True, null=True, verbose_name="SQL Notes"),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Modified Timestamp"
                    ),
                ),
            ],
            options={"db_table": "utl_sql_queries",},
        ),
        migrations.AddField(
            model_name="dme_files",
            name="file_path",
            field=models.TextField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="api_booking_quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="file_extension",
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="file_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="file_type",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="note",
            field=models.TextField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="z_createdByAccount",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="dme_files",
            name="z_createdTimeStamp",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dme_reports",
            name="z_downloadedTimeStamp",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Downloaded Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="utl_states",
            name="fk_country_id",
            field=models.CharField(blank=True, default="", max_length=32, null=True),
        ),
    ]
