# Generated by Django 2.1.2 on 2020-03-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0183_auto_20200317_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_process_mgr",
            name="origin_puPickUpAvailFrom_Date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Origin PU Available From Date",
            ),
        ),
        migrations.AddField(
            model_name="client_process_mgr",
            name="origin_pu_PickUp_Avail_Time_Minutes",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Origin PU Available Time Minutes",
            ),
        ),
        migrations.AddField(
            model_name="client_process_mgr",
            name="origin_pu_PickUp_By_Time_Hours",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Origin PU By Time Hours"
            ),
        ),
        migrations.AddField(
            model_name="client_process_mgr",
            name="origin_pu_PickUp_By_Time_Minutes",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Origin PU By Time Minutes",
            ),
        ),
        migrations.AddField(
            model_name="dme_clients",
            name="augment_pu_available_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="dme_clients",
            name="augment_pu_by_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_Street_1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=80,
                null=True,
                verbose_name="PU Address Street 1",
            ),
        ),
    ]
