# Generated by Django 2.1.2 on 2020-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_auto_20200320_1259'),
        ('api', '0183_auto_20200313_0111'),
    ]

    operations = [
    ]
