# Generated by Django 2.1.2 on 2020-03-25 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0185_merge_20200325_1309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_employees",
            name="fk_id_dme_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.DME_clients",
            ),
        ),
        migrations.AlterField(
            model_name="client_employees",
            name="fk_id_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client_employees",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.DME_Roles",
            ),
        ),
    ]
