# Generated by Django 2.1.2 on 2020-03-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0186_auto_20200325_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_006_b_created_for_email",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="b_006_b_created_for_email",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_Created_For_Email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="Booking Created For Email",
            ),
        ),
        migrations.AlterField(
            model_name="client_employees",
            name="email",
            field=models.EmailField(
                max_length=64, null=True, unique=True, verbose_name="email address"
            ),
        ),
    ]
