# Generated by Django 2.1.2 on 2020-03-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0187_auto_20200325_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dme_status_history",
            name="status_last",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Status Last"
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="status_old",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Status Old"
            ),
        ),
    ]
