# Generated by Django 2.1.2 on 2020-03-29 23:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0188_auto_20200327_0022"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rule_type_code",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "calc_type",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "charge_rule",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
            ],
            options={"db_table": "rule_types",},
        ),
        migrations.AddField(
            model_name="fp_freight_providers",
            name="rule_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.RuleTypes",
            ),
        ),
    ]
