# Generated by Django 2.1.2 on 2020-03-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0189_auto_20200329_2332"),
    ]

    operations = [
        migrations.RemoveField(model_name="fp_pricing_rules", name="calc_type",),
        migrations.RemoveField(model_name="fp_pricing_rules", name="charge_rule",),
    ]
