# Generated by Django 2.1.2 on 2020-04-01 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0189_auto_20200330_1144"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_Service_Codes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_code",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        default=None, max_length=64, verbose_name="Created by account"
                    ),
                ),
                (
                    "z_createdTimestamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_modifiedTimestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Created Timestamp",
                    ),
                ),
            ],
            options={"db_table": "dme_service_codes",},
        ),
        migrations.AddField(
            model_name="fp_freight_providers",
            name="service_cutoff_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
