# Generated by Django 2.1.2 on 2020-04-01 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0190_auto_20200401_0311"),
    ]

    operations = [
        migrations.CreateModel(
            name="FP_Service_ETDs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fp_delivery_service_code",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "fp_delivery_time_description",
                    models.TextField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "fp_service_time_uom",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "fp_03_delivery_hours",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        default=None, max_length=64, verbose_name="Created by account"
                    ),
                ),
                (
                    "z_createdTimestamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_modifiedTimestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Created Timestamp",
                    ),
                ),
                (
                    "dme_service_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.DME_Service_Codes",
                    ),
                ),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={"db_table": "fp_service_etds",},
        ),
    ]
