# Generated by Django 2.1.2 on 2020-04-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_auto_20200329_2344'),
        ('api', '0191_auto_20200401_0348'),
    ]

    operations = [
    ]
