# Generated by Django 2.1.2 on 2020-04-01 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0192_merge_20200401_2323"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("booking_ids", models.TextField(blank=True, default=None, null=True)),
                (
                    "note",
                    models.TextField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        default=None, max_length=64, verbose_name="Created by account"
                    ),
                ),
                (
                    "z_createdTimestamp",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_modifiedTimestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Created Timestamp",
                    ),
                ),
            ],
            options={"db_table": "dme_booking_sets",},
        ),
    ]
