# Generated by Django 2.1.2 on 2020-04-06 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0192_merge_20200405_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_puCompany",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Origin PU Company"
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_pu_Address_Street_1",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Origin PU Address Street1"
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_pu_Address_Street_2",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Origin PU Address Street2"
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="process_name",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Process Name"
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="z_createdTimeStamp",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Created Timestamp",
            ),
        ),
    ]
