# Generated by Django 2.1.2 on 2020-04-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_auto_20200401_2323'),
        ('api', '0193_auto_20200406_1423'),
    ]

    operations = [
    ]
