# Generated by Django 2.1.2 on 2020-04-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0194_merge_20200417_0329"),
    ]

    operations = [
        migrations.RemoveField(model_name="fp_pricing_rules", name="timing",),
        migrations.AddField(
            model_name="fp_pricing_rules",
            name="etd",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.FP_Service_ETDs",
            ),
        ),
        migrations.DeleteModel(name="FP_timings",),
    ]
