# Generated by Django 2.1.2 on 2020-04-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0196_auto_20200417_1443"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client_auto_augment", name="sales_club_de_Email",
        ),
        migrations.RemoveField(
            model_name="client_auto_augment", name="sales_club_de_Email_Group_Emails",
        ),
        migrations.RemoveField(model_name="client_auto_augment", name="tic_de_Email",),
        migrations.RemoveField(
            model_name="client_auto_augment", name="tic_de_Email_Group_Emails",
        ),
        migrations.RemoveField(
            model_name="client_auto_augment", name="tic_de_To_Address_Street_1",
        ),
        migrations.RemoveField(
            model_name="client_auto_augment", name="tic_de_To_Address_Street_2",
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="company_hours_info",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="de_Email",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="de_Email_Group_Emails",
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="de_To_Address_Street_1",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="de_To_Address_Street_2",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="de_to_companyName",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="client_auto_augment",
            name="fk_id_dme_client",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.DME_clients",
            ),
        ),
    ]
