# Generated by Django 2.1.2 on 2020-04-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0197_auto_20200420_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsets",
            name="auto_select_type",
            field=models.BooleanField(
                blank=True, default=True, max_length=255, null=True
            ),
        ),
    ]
