# Generated by Django 2.1.2 on 2020-05-09 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0198_auto_20200424_0145"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tokens",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(default=None, max_length=255)),
                ("type", models.CharField(default=None, max_length=255)),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        default=datetime.datetime(2020, 5, 9, 3, 37, 28, 973233)
                    ),
                ),
                ("z_expiryTimeStamp", models.DateTimeField(default=None)),
            ],
            options={"db_table": "tokens",},
        ),
    ]
