# Generated by Django 2.1.2 on 2020-05-19 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0200_auto_20200520_0312"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_employees",
            name="status_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, verbose_name="Status Time"
            ),
        ),
    ]
