# Generated by Django 2.1.2 on 2020-06-11 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0201_auto_20200520_0400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_lines",
            name="z_modifiedTimeStamp",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Modified Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines_data",
            name="z_modifiedTimeStamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_ModifiedTimestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
