# Generated by Django 2.1.2 on 2020-06-16 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0203_auto_20200616_0210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="z_CreatedTimestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_ModifiedByAccount",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Modified By Account"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_ModifiedTimestamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
