# Generated by Django 2.1.2 on 2020-06-18 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0205_auto_20200616_0234"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_Ras",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ra_number", models.CharField(blank=True, max_length=30, null=True)),
                ("dme_number", models.CharField(blank=True, max_length=50, null=True)),
                ("name_first", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "name_surname",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "phone_mobile",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("address1", models.CharField(blank=True, max_length=80, null=True)),
                ("address2", models.CharField(blank=True, max_length=80, null=True)),
                ("suburb", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=30, null=True)),
                ("state", models.CharField(blank=True, max_length=25, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "item_model_num",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_in_box",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
                (
                    "fk_id_dme_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.DME_clients",
                    ),
                ),
            ],
            options={"db_table": "client_ras",},
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_send_POD_eMail",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
