# Generated by Django 2.1.2 on 2020-07-02 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0206_auto_20200618_0307"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_options",
            name="arg1",
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
