# Generated by Django 2.1.2 on 2020-07-03 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0207_auto_20200702_0320"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_options",
            name="arg2",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
