# Generated by Django 2.1.2 on 2020-07-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0208_auto_20200703_0200"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_Error",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accountCode", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "fk_booking_id",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Booking ID"
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "error_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={"db_table": "dme_errors",},
        ),
    ]
