# Generated by Django 2.1.2 on 2020-07-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0209_auto_20200715_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="inv_sell_quoted_override",
            field=models.FloatField(blank=True, default=None, null=True),
        )
    ]
