# Generated by Django 2.1.2 on 2020-08-31 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0212_auto_20200803_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_020_b_pu_num_operators",
            field=models.PositiveIntegerField(
                blank=True,
                default=False,
                null=True,
                verbose_name="b_020_b_pu_num_operators",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_042_b_del_num_operators",
            field=models.PositiveIntegerField(
                blank=True,
                default=False,
                null=True,
                verbose_name="b_042_b_del_num_operators",
            ),
        ),
    ]
