# Generated by Django 2.1.2 on 2020-08-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0212_auto_20200803_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
    ]
