# Generated by Django 2.1.2 on 2020-09-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_auto_20200805_0712'),
        ('api', '0213_auto_20200831_0147'),
    ]

    operations = [
    ]
