# Generated by Django 2.1.2 on 2020-09-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0214_merge_20200917_0117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="ld_006_insurance_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Insurance Value"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines_data",
            name="insuranceValueEach",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Insurance Value Each"
            ),
        ),
        migrations.AddField(
            model_name='dme_options',
            name='show_in_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        )
    ]
