# Generated by Django 2.1.2 on 2020-10-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0215_auto_20200917_0117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client_products",
            name="modelNumber",
        ),
        migrations.AddField(
            model_name="client_products",
            name="child_model_number",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="client_products",
            name="parent_model_number",
            field=models.CharField(default=None, max_length=64),
        ),
    ]
