# Generated by Django 2.1.2 on 2020-10-08 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0219_auto_20201005_0151"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="picked_up_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Picked up timestamp at Warehouse",
            ),
        ),
    ]
