# Generated by Django 2.1.2 on 2020-11-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_auto_20200930_0055'),
        ('api', '0220_auto_20201008_0152'),
    ]

    operations = [
    ]
