# Generated by Django 2.1.2 on 2020-11-06 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0222_auto_20201101_0038"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_2_lines",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
