# Generated by Django 2.1.2 on 2020-11-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0223_auto_20201106_0122"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_warehouses",
            name="use_dme_label",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_address1",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_address2",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_phone_main",
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_postal_code",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_state",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehouse_suburb",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="warehousename",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
