# Generated by Django 2.1.2 on 2020-12-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0224_auto_20201125_0206"),
    ]

    operations = [
        migrations.RenameField(
            model_name="api_booking_quotes",
            old_name="fk_freight_provider_id",
            new_name="freight_provider",
        ),
    ]
