# Generated by Django 2.1.2 on 2020-12-09 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0226_auto_20201209_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_booking_confirmation_lines",
            name="client_item_reference",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="api_booking_confirmation_lines",
            name="fp_scan_data",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_0_bookingkeys",
            name="client",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_000_3_consignment_number",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_059_b_del_address_postalcode",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                verbose_name="Address Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_client_del_note_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Del Note Num",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_client_order_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Order Num",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_client_sales_inv_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Sales Inv Num",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_client_warehouse_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Warehouse code",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="fp_pu_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Warehouse code",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="z_test",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_101_text_1",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_102_text_2",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_103_text_3",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_104_text_4",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_105_text_5",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="client_item_number",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="client_item_reference",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="l_008_weight_UOM",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="DIM Weight",
            ),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="zbl_101_text_1",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="zbl_102_text_2",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="zbl_103_text_3",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="zbl_104_text_4",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="zbl_105_text_5",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_101_text_1",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_102_text_2",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_103_text_3",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_104_text_4",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_105_text_5",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="client_item_reference",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="DME_Notes",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="DME Notes",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="api_booking_quote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_ImportedFromFile",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Imported File Filed",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_Category",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Categroy",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_Notes",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=400,
                null=True,
                verbose_name="Booking Notes",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_Priority",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name="Booking Priority",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_status_manual",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Booking Status Manual",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_status_manual_DME",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=2,
                null=True,
                verbose_name="Booking Status Manual DME",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_booking_statusmanual_DME_Note",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Booking Status Manual DME Note",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_clientPU_Warehouse",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name="warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_clientReference_RA_Numbers",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                verbose_name="Client Reference Ra Numbers",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_Reference_RA_Numbers_lastupdate",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Client Reference RA Number Last Update",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_booking_ref_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Ref Num",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_del_note_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Del Note Num",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=36,
                null=True,
                verbose_name="Client Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_order_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Order Num",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_sales_inv_num",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Sales Inv Num",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_client_warehouse_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Warehouse code",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_dateBookedDate",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Booked Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_date_booked_by_dme",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date Booked By DME"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_dateinvoice",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date Invoice"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_email_Template_Name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Email Template Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_error_Capture",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                verbose_name="Error Capture",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_error_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="Error Code",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_handling_Instructions",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=120,
                null=True,
                verbose_name="Handling Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_order_created",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=45,
                null=True,
                verbose_name="Order Created",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_status",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_status_API",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Status API",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_status_sub_client",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_status_sub_fp",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booked_for_comm_communicate_via",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=120,
                null=True,
                verbose_name="Booked Communicate Via",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_Created_For",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="Booking Created For",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_Created_For_Email",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Created For Email",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_api_end_TimeStamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="booking_api_start_TimeStamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="consignment_label_link",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=250,
                null=True,
                verbose_name="Consignment",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="deToCompanyName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Contact",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="DE Contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Deliver_By_Date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="DE By Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Deliver_From_Date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="DE From Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Email",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="DE Email",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Email_Group_Emails",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="DE Email Group Emails",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Email_Group_Name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Email Group Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Operating_Hours",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="DE Operating hours",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_Options",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Options",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_TimeSlot_TimeStart",
            field=models.TimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="DE TimeSlot TimeStart",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_TimeSlot_Time_End",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="TimeSlot Time End"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_AddressType",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="DE Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_City",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="DE Address City",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_Country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=12,
                null=True,
                verbose_name="DE Address Country",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_PostalCode",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Address Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_State",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="DE Address State",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_Street_1",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="DE Address Street 1",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_Street_2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="DE Address Street 2",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Address_Suburb",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="DE Address Suburb",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_To_Comm_Delivery_Communicate_Via",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="DE Communicate Via",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Contact_FName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="DE Contact First Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Contact_F_LName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="DE Contact Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Contact_Lname",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="DE Contact Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Phone_Main",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Phone Main",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Phone_Mobile",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="DE Phone Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_PickUp_Instructions_Address",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="DE Instructions Address",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_Pick_Up_Instructions_Contact",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="DE Instructions Contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_TimeSlot_Date_End",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="DE to TimeSlot Date End",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_WareHouse_Bay",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="DE Warehouse Bay",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_WareHouse_Number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Warehouse Number",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="dme_status_action",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="dme_status_detail",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="dme_status_detail_updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="dme_status_detail_updated_by",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="dme_status_linked_reference_from_fp",
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="error_details",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=250,
                null=True,
                verbose_name="Error Detail",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="fk_fp_pickup_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="KF FP pickup id",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="fp_store_event_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="fp_store_event_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_billing_status",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_billing_status_note",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="inv_dme_invoice_no",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Invoice Num Booking",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_Add_ID_DE",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Add ID Deliver",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_Add_ID_PU",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Add ID Pick Up",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_FP_ID",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="FP ID"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_booking_Created_For_ID",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Created For ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_booking_quote_import_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Quote Import ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_clientCustomerID_DE",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Custom ID Deliver",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_clientCustomerID_PU",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Custom ID Pick Up",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_client_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="KF Client ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_email_Template",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Email Template",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_order_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="kf_staff_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Staff ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="manifest_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="notes_cancel_Booking",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Notes Cancel Booking",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pk_booking_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="prev_dme_status_detail",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="puCompany",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="puPickUpAvailFrom_Date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="PickUp Available From",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Actual_Date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="PU Actual Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Actual_PickUp_Time",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Actual PU Time"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_City",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="PU Address City",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_Country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="PU Address Country",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_PostalCode",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Address Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_State",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Address State",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_Street_1",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=80,
                null=True,
                verbose_name="PU Address Street 1",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_Suburb",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="PU Address Suburb",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_Type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Address Type",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Address_street_2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="PU Address Street 2",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Comm_Booking_Communicate_Via",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Booking Communicate Via",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Contact_FName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Contact First Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Contact_F_L_Name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Contact Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Contact_Lname",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Contact Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Email",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="PU Email",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Operting_Hours",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="PU Operating hours",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Phone_Main",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Phone Main",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_Phone_Mobile",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Phone Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_Avail_From_Date_DME",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="PU Available From Date DME",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_By_Date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="PickUp By Date"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_By_Date_DME",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="PU By Date DME"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_Instructions_Contact",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="PU Instructions Contact",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_PickUp_TimeSlot_TimeEnd",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="PU TimeSlot TimeEnd"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_WareHouse_Bay",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="PU Warehouse Bay",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_WareHouse_Number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="PU Warehouse Number",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_email_Group",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="PU Email Group",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_email_Group_Name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="PU Email Group Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="pu_pickup_instructions_address",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="Pickup instrunctions address",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="rpt_pod_from_file_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="rpt_proof_of_del_from_csv_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_02_Booking_Cutoff_Time",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Booking Cutoff Time"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_05_LatestPickUpDateTimeFinal",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Lastest PickUp DateTime",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_05_Latest_PickUp_Date_Time_Override",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Latest PU DateTime Override",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_05_Latest_Pick_Up_Date_TimeSet",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Latest PU DateTime Set",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_06_LatestDeliveryDateTimeFinal",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Latest Delivery DateTime",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_06_Latest_Delivery_Date_TimeSet",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Latest DE DateTime Set",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_06_Latest_Delivery_Date_Time_Override",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Latest DE DateTime Override",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_07_PickUp_Progress",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="PU Progress",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_08_Delivery_Progress",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="DE Progress",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_20_Actual_Pickup_TimeStamp",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Actual PU TimeStamp"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_21_ActualDeliveryTimeStamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Actual Delivery Timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="s_21_Actual_Delivery_TimeStamp",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Actual DE TimeStamp"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="shipping_label_base64",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Based64 Label",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_FPBookingNumber",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="FP Booking Number",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_customer_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=20,
                null=True,
                verbose_name="Customer Code",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_serviceCode_DME",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="Service Code DME",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_serviceTime_End",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Service Time End"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_serviceTime_Start",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Service Time Start"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_service_Type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="Service Type",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_service_Type_2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Service Type 2",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_service_Type_ID",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Service Type ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="v_vehicle_Type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Vehicle Type",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_account_code",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_fp_del_eta_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="FP Delivery ETA Time"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_fp_order_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Order ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_fp_pu_eta_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="FP PickUp ETA Time"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_freight_provider",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Freight Provider",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_freight_time",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Freight Time"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_futile_Booking_Notes",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Futile Booking Notes",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_serviceName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Service Name",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="vx_service_Name_ID",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Service Name ID",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="x_Data_Entered_Via",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Data Entered Via",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="x_ReadyStatus",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name="Ready Status",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="x_booking_Created_With",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name="Booking Created With",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_CreatedByAccount",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Created By Account",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_ModifiedByAccount",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="Modified By Account",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_Notes_Bugs",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Notes Bugs",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_admin_dme_invoice_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=25,
                null=True,
                verbose_name="Admin DME Invoice Number",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_calculated_ETA",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_connote_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_downloaded_connote_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_downloaded_pod_sog_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_downloaded_pod_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_downloaded_shipping_label_timestamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="downloaded_shipping_label_timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_included_with_manifest_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Included With Manifest Date",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_label_url",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="PDF Url",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_lastStatusAPI_ProcessedTimeStamp",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Last StatusAPI Processed Timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_locked_status_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_manifest_url",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Manifest URL",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_manual_booking_set_time_push_to_fm",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_manual_booking_set_to_confirm",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_pod_signed_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_pod_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="z_status_process_notes",
            field=models.TextField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="zb_002_client_booking_key",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Client Booking Key",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="fk_booking_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking ID",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_deToCompanyName",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Origin DE Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_de_Email",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Origin DE Email",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_de_To_Address_Street_1",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="Origin DE Address Street 1",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_de_To_Address_Street_2",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=40,
                null=True,
                verbose_name="Origin DE Address Street 2",
            ),
        ),
        migrations.AlterField(
            model_name="client_process_mgr",
            name="origin_pu_pickup_instructions_address",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="Origin PU instrunctions address",
            ),
        ),
        migrations.AlterField(
            model_name="dme_clients",
            name="dme_account_num",
            field=models.CharField(
                default=None, max_length=64, verbose_name="dme account num"
            ),
        ),
        migrations.AlterField(
            model_name="dme_label_settings",
            name="uom",
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="dme_log_addr",
            name="addresses",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Address Info"
            ),
        ),
        migrations.AlterField(
            model_name="dme_log_addr",
            name="consignmentNumber",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Consignment Number",
            ),
        ),
        migrations.AlterField(
            model_name="dme_log_addr",
            name="fk_booking_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="depot_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Depot Name",
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="dme_notes",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="DME notes",
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="dme_status_action",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="dme_status_detail",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="dme_status_linked_reference_from_fp",
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="fk_fp_id",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="FP ID"
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Recipient Name",
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="status_code_api",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Status Code API",
            ),
        ),
        migrations.AlterField(
            model_name="dme_status_history",
            name="status_from_api",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Status From API",
            ),
        ),
        migrations.AlterField(
            model_name="dme_utl_fp_statuses",
            name="fp_status_description",
            field=models.TextField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="fk_service_provider_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=36,
                verbose_name="Service Provider ID",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="request_payload",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=2000,
                verbose_name="Request Payload",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="request_status",
            field=models.CharField(
                blank=True, default=None, max_length=20, verbose_name="Request Status"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="request_type",
            field=models.CharField(
                blank=True, default=None, max_length=30, verbose_name="Request Type"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="response",
            field=models.TextField(
                blank=True, default=None, max_length=10000, verbose_name="Response"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="z_createdBy",
            field=models.CharField(
                blank=True, default=None, max_length=40, verbose_name="Created By"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="z_modifiedBy",
            field=models.CharField(
                blank=True, default=None, max_length=40, verbose_name="Modified By"
            ),
        ),
        migrations.AlterField(
            model_name="utl_states",
            name="fk_country_id",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
