# Generated by Django 2.1.2 on 2021-01-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0230_auto_20210105_0023"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="log",
        #     name="z_createdBy",
        # ),
        # migrations.RemoveField(
        #     model_name="log",
        #     name="z_modifiedBy",
        # ),
    ]
