# Generated by Django 2.1.2 on 2021-01-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0231_auto_20210105_0028"),
    ]

    operations = []
