# Generated by Django 2.1.2 on 2021-01-12 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0232_merge_20210112_0708"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client_FP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.DME_clients",
                    ),
                ),
                (
                    "fp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={
                "db_table": "client_fp",
            },
        )
    ]
