# Generated by Django 2.1.2 on 2021-01-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0233_auto_20210112_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fc_log",
            name="new_quote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api.API_booking_quotes",
            ),
        ),
        migrations.AlterField(
            model_name="fc_log",
            name="old_quote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api.API_booking_quotes",
            ),
        ),
    ]
