# Generated by Django 2.1.2 on 2021-02-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_auto_20210113_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_067_assembly_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_068_b_del_location',
            field=models.CharField(choices=[('Drop at Door / Warehouse Dock', 'Drop at Door / Warehouse Dock'), ('Drop in Door / Warehouse', 'Drop in Door / Warehouse'), ('Room of Choice', 'Room of Choice')], default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_069_b_del_floor_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_070_b_del_floor_access_by',
            field=models.CharField(choices=[('Elevator', 'Elevator'), ('Escalator', 'Escalator'), ('Stairs', 'Stairs')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_071_b_del_sufficient_space',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_assembly_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_floor_access_by',
            field=models.CharField(choices=[('Elevator', 'Elevator'), ('Escalator', 'Escalator'), ('Stairs', 'Stairs')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_floor_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_location',
            field=models.CharField(choices=[('Drop at Door / Warehouse Dock', 'Drop at Door / Warehouse Dock'), ('Drop in Door / Warehouse', 'Drop in Door / Warehouse'), ('Room of Choice', 'Room of Choice')], default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='de_to_sufficient_space',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
