# Generated by Django 2.1.2 on 2021-01-25 03:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0235_auto_20210125_0233"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingcostoption",
            name="qty",
            field=models.FloatField(default=1, null=True),
        ),
    ]
