# Generated by Django 2.1.2 on 2021-01-29 05:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_auto_20210125_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcostoption',
            name='markup_percentage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='costoption',
            name='initial_markup_percentage',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='costoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
