# Generated by Django 2.1.2 on 2021-02-02 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_auto_20210129_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_address2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_hours',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehousename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_phone_main',
            new_name='phone_main',
        ),
        migrations.RenameField(
            model_name='client_warehouses',
            old_name='warehouse_suburb',
            new_name='suburb',
        ),
        migrations.AddField(
            model_name='client_warehouses',
            name='contact_name',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client_warehouses',
            name='contact_email',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
