# Generated by Django 2.1.2 on 2021-02-10 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0239_auto_20210202_0554"),
    ]

    operations = [
        migrations.CreateModel(
            name="FPRouting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("suburb", models.CharField(default=None, max_length=45, null=True)),
                ("state", models.CharField(default=None, max_length=45, null=True)),
                (
                    "dest_postcode",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                (
                    "orig_depot",
                    models.CharField(default=None, max_length=10, null=True),
                ),
                (
                    "orig_depot_except",
                    models.CharField(default=None, max_length=10, null=True),
                ),
                ("gateway", models.CharField(default=None, max_length=10, null=True)),
                ("onfwd", models.CharField(default=None, max_length=10, null=True)),
                ("sort_bin", models.CharField(default=None, max_length=10, null=True)),
                (
                    "orig_postcode",
                    models.CharField(default=None, max_length=10, null=True),
                ),
                (
                    "service_group",
                    models.CharField(default=None, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "fp_routing",
            },
        ),
    ]
