# Generated by Django 2.1.2 on 2021-02-10 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0240_auto_20210210_0115"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fprouting",
            old_name="service_group",
            new_name="routing_group",
        ),
    ]
