# Generated by Django 2.1.2 on 2021-02-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_auto_20210203_0125'),
        ('api', '0241_auto_20210210_0121'),
    ]

    operations = [
    ]
