# Generated by Django 2.1.2 on 2021-02-10 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0242_merge_20210210_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_003_b_service_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Service Name"
            ),
        ),
    ]
