# Generated by Django 2.1.2 on 2021-02-28 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0243_auto_20210210_0845"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_clients",
            name="gap_percent",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
