# Generated by Django 2.1.2 on 2021-03-18 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0244_auto_20210228_0300"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_072_b_pu_no_of_assists",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_073_b_del_no_of_assists",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_074_b_pu_delivery_access",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_075_b_del_delivery_access",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_076_b_pu_service",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_077_b_del_service",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_078_b_pu_location",
            field=models.CharField(
                choices=[
                    ("Drop at Door / Warehouse Dock", "Drop at Door / Warehouse Dock"),
                    ("Drop in Door / Warehouse", "Drop in Door / Warehouse"),
                    ("Room of Choice", "Room of Choice"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_079_b_pu_floor_number",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_080_b_pu_floor_access_by",
            field=models.CharField(
                choices=[
                    ("Elevator", "Elevator"),
                    ("Escalator", "Escalator"),
                    ("Stairs", "Stairs"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="zbl_121_integer_1",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
