# Generated by Django 2.1.2 on 2021-04-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0247_auto_20210408_0244"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlliedETD",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("syd", models.FloatField(default=None, null=True)),
                ("mel", models.FloatField(default=None, null=True)),
                ("bne", models.FloatField(default=None, null=True)),
                ("adl", models.FloatField(default=None, null=True)),
                ("per", models.FloatField(default=None, null=True)),
                (
                    "zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.FP_zones",
                    ),
                ),
            ],
            options={
                "db_table": "allied_etd",
            },
        ),
    ]
