# Generated by Django 2.1.2 on 2021-04-01 02:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0248_auto_20210401_0102"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_3_lines_data",
            name="is_deleted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
