# Generated by Django 2.1.2 on 2021-04-19 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0248_auto_20210408_0246"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_status_category",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
