# Generated by Django 2.1.2 on 2021-04-20 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0249_auto_20210419_0050"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(default=None, max_length=64, null=True)),
                ("type", models.CharField(default=None, max_length=64, null=True)),
                ("desc", models.CharField(default=None, max_length=254, null=True)),
                ("length", models.FloatField(default=None, null=True)),
                ("width", models.FloatField(default=None, null=True)),
                ("height", models.FloatField(default=None, null=True)),
                ("weight", models.FloatField(default=None, null=True)),
                ("max_weight", models.FloatField(default=None, null=True)),
            ],
            options={
                "db_table": "utl_pallet",
            },
        ),
    ]
