# Generated by Django 2.1.2 on 2021-04-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_auto_20210401_0213'),
        ('api', '0250_auto_20210420_2339'),
    ]

    operations = [
    ]
