# Generated by Django 2.1.2 on 2021-04-23 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0251_merge_20210423_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_freight_providers",
            name="hex_color_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
