# Generated by Django 2.1.2 on 2021-04-28 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0253_auto_20210428_0056"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsets",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.FP_vehicles",
            ),
        ),
    ]
