# Generated by Django 2.1.2 on 2021-05-04 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0254_auto_20210428_0231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_3_lines_data",
            name="zbld_105_text_5",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
