# Generated by Django 2.1.2 on 2021-05-06 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0255_auto_20210504_0134"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_068_b_del_location",
            field=models.CharField(
                choices=[
                    (
                        "Pickup at Door / Warehouse Dock",
                        "Pickup at Door / Warehouse Dock",
                    ),
                    ("Drop at Door / Warehouse Dock", "Drop at Door / Warehouse Dock"),
                    ("Drop in Door / Warehouse", "Drop in Door / Warehouse"),
                    ("Room of Choice", "Room of Choice"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_070_b_del_floor_access_by",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("Elevator", "Elevator"),
                    ("Escalator", "Escalator"),
                    ("Stairs", "Stairs"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_078_b_pu_location",
            field=models.CharField(
                choices=[
                    (
                        "Pickup at Door / Warehouse Dock",
                        "Pickup at Door / Warehouse Dock",
                    ),
                    ("Drop at Door / Warehouse Dock", "Drop at Door / Warehouse Dock"),
                    ("Drop in Door / Warehouse", "Drop in Door / Warehouse"),
                    ("Room of Choice", "Room of Choice"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_080_b_pu_floor_access_by",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("Elevator", "Elevator"),
                    ("Escalator", "Escalator"),
                    ("Stairs", "Stairs"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
