# Generated by Django 2.1.2 on 2021-05-12 02:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0256_auto_20210506_0543"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(default=None, max_length=16, null=True)),
                ("state", models.CharField(default=None, max_length=16, null=True)),
                ("name", models.CharField(default=None, max_length=128, null=True)),
                ("range", models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                "db_table": "postal_code",
            },
        ),
    ]
