# Generated by Django 2.1.2 on 2021-06-01 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0258_auto_20210526_0028"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="DME_price_from_client",
        ),
        migrations.AddField(
            model_name="bookings",
            name="client_overrided_quote",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
