# Generated by Django 2.1.2 on 2021-06-01 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0259_auto_20210601_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_090_client_overrided_quote",
            field=models.FloatField(default=None, null=True),
        ),
    ]
