# Generated by Django 2.1.2 on 2021-06-02 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0260_auto_20210601_1422"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bok_1_headers",
            name="b_090_client_overrided_quote",
        ),
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_091_send_quote_to_pronto",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
