# Generated by Django 2.1.2 on 2021-06-03 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0261_auto_20210602_2352"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="zbl_102_text_2",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        )
    ]
