# Generated by Django 2.1.2 on 2021-06-09 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0262_auto_20210603_0823"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surcharge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default=None, max_length=128, null=True)),
                ("amount", models.FloatField(default=None, null=True)),
                ("line_id", models.CharField(default=None, max_length=32, null=True)),
                ("qty", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "fp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.API_booking_quotes",
                    ),
                ),
            ],
            options={
                "db_table": "dme_surcharge",
            },
        ),
    ]
