# Generated by Django 2.1.2 on 2021-06-09 06:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0263_auto_20210609_0541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="line_id",
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="surcharge",
            name="name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
