# Generated by Django 2.1.2 on 2021-06-10 03:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0264_auto_20210609_0633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_booking_quotes",
            name="x_price_surcharge",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Price Surcharge"
            ),
        )
    ]
