# Generated by Django 2.1.2 on 2021-06-14 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0265_auto_20210610_0306"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_quotes",
            name="fuel_levy_base",
            field=models.FloatField(blank=True, default=0, null=True),
        )
    ]
