# Generated by Django 2.1.2 on 2021-06-14 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0266_auto_20210614_0212"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_quotes",
            name="client_mark_up_percent",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
