# Generated by Django 2.1.2 on 2021-06-15 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0267_auto_20210614_0246"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_092_booking_type",
            field=models.CharField(
                choices=[("DMEM", "DMEM"), ("DMEA", "DMEA")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="booking_type",
            field=models.CharField(
                choices=[("DMEM", "DMEM"), ("DMEA", "DMEA")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
    ]
