# Generated by Django 2.1.2 on 2021-06-28 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0268_auto_20210615_2314"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_products",
            name="is_ignored",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
