# Generated by Django 2.1.2 on 2021-07-01 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0269_auto_20210628_0557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_105_text_5",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
