# Generated by Django 2.1.2 on 2021-07-02 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0270_auto_20210701_0132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="zb_105_text_5",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
