# Generated by Django 2.1.2 on 2021-07-08 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0271_auto_20210702_0047"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_quotes",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.FP_vehicles",
            ),
        )
    ]
