# Generated by Django 2.1.2 on 2021-07-26 05:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0272_auto_20210708_2333"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="de_to_floor_number",
            new_name="de_floor_number",
        ),
        migrations.AddField(
            model_name="bookings",
            name="de_access",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="de_no_of_assists",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="de_service",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_access",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_floor_access_by",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("Elevator", "Elevator"),
                    ("Escalator", "Escalator"),
                    ("Stairs", "Stairs"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_floor_number",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_location",
            field=models.CharField(
                choices=[
                    (
                        "Pickup at Door / Warehouse Dock",
                        "Pickup at Door / Warehouse Dock",
                    ),
                    ("Drop at Door / Warehouse Dock", "Drop at Door / Warehouse Dock"),
                    ("Drop in Door / Warehouse", "Drop in Door / Warehouse"),
                    ("Room of Choice", "Room of Choice"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_no_of_assists",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="pu_service",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_floor_access_by",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("Elevator", "Elevator"),
                    ("Escalator", "Escalator"),
                    ("Stairs", "Stairs"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="de_to_location",
            field=models.CharField(
                choices=[
                    (
                        "Pickup at Door / Warehouse Dock",
                        "Pickup at Door / Warehouse Dock",
                    ),
                    ("Drop at Door / Warehouse Dock", "Drop at Door / Warehouse Dock"),
                    ("Drop in Door / Warehouse", "Drop in Door / Warehouse"),
                    ("Room of Choice", "Room of Choice"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
    ]
