# Generated by Django 2.1.2 on 2021-07-25 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0272_auto_20210708_2333"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="packed_status",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("auto", "auto"),
                    ("manual", "manual"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
