# Generated by Django 2.1.2 on 2021-07-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0273_auto_20210725_0016'),
        ('api', '0273_auto_20210726_0551'),
    ]

    operations = [
    ]
