# Generated by Django 2.1.2 on 2021-08-05 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0275_auto_20210804_0301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="booking_type",
            field=models.CharField(
                choices=[("DMEM", "DMEM"), ("DMEA", "DMEA"), ("DMEP", "DMEP")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
    ]
