# Generated by Django 2.1.2 on 2021-08-06 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0276_auto_20210805_2242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_092_booking_type",
            field=models.CharField(
                choices=[("DMEM", "DMEM"), ("DMEA", "DMEA"), ("DMEP", "DMEP")],
                default=None,
                max_length=4,
                null=True,
            ),
        )
    ]
