# Generated by Django 2.1.2 on 2021-08-22 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_auto_20210806_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp_pricing_rules',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DME_clients'),
        )
    ]
