# Generated by Django 2.1.2 on 2021-08-29 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0279_auto_20210829_1651"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="fp_status_history",
            table="fp_status_history",
        ),
    ]
