# Generated by Django 2.1.2 on 2021-08-30 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0280_auto_20210829_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fp_status_history",
            name="desc",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
