# Generated by Django 2.1.2 on 2021-08-30 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0281_auto_20210830_0147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fp_status_history",
            name="desc",
            field=models.TextField(default=None, null=True),
        ),
    ]
