# Generated by Django 2.1.2 on 2021-08-30 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0282_auto_20210830_0152"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_clients",
            name="logo_url",
            field=models.CharField(
                default=None, max_length=200, null=True, verbose_name="Logo Url"
            ),
        ),
    ]
