# Generated by Django 2.1.2 on 2021-09-05 23:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0283_auto_20210830_2347"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZohoTicketSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("summary", models.TextField(default=None, null=True)),
                (
                    "z_createdAt",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                "db_table": "zoho_ticket_summary",
            },
        ),
    ]
