# Generated by Django 2.1.2 on 2021-09-14 00:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0284_auto_20210905_2344"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_quotes",
            name="packed_status",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("auto", "auto"),
                    ("manual", "manual"),
                    ("scanned", "scanned"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="packed_status",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("auto", "auto"),
                    ("manual", "manual"),
                    ("scanned", "scanned"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
