# Generated by Django 2.1.2 on 2021-09-27 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0285_auto_20210914_0013"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_clients",
            name="status_email",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="dme_clients",
            name="status_phone",
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name="dme_clients",
            name="status_send_flag",
            field=models.BooleanField(default=False),
        ),
    ]
