# Generated by Django 2.1.2 on 2021-10-07 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0287_auto_20210930_0141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="booking_Created_For",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Booking Created For",
            ),
        ),
    ]
