# Generated by Django 2.1.2 on 2021-10-25 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0288_auto_20211007_0800"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="bok_1_headers",
        #     name="b_093_packed_status",
        # ),
        migrations.AddField(
            model_name="bok_2_lines",
            name="b_093_packed_status",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("auto", "auto"),
                    ("manual", "manual"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
