# Generated by Django 2.1.2 on 2021-10-26 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0288_auto_20211007_0800"),
    ]

    operations = [
        migrations.AddField(
            model_name="fprouting",
            name="freight_provider",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Fp_freight_providers",
            ),
        )
    ]
