# Generated by Django 2.1.2 on 2021-11-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0289_auto_20211026_0626'),
        ('api', '0289_auto_20211025_0820'),
    ]

    operations = [
    ]
