# Generated by Django 2.1.2 on 2021-12-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0291_auto_20211115_0405"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_costs",
            name="max_volume",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
