# Generated by Django 2.1.2 on 2021-12-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0292_auto_20211215_0005"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fprouting",
            old_name="state",
            new_name="dest_state",
        ),
        migrations.RenameField(
            model_name="fprouting",
            old_name="suburb",
            new_name="dest_suburb",
        ),
        migrations.AddField(
            model_name="fprouting",
            name="data_code",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
