# Generated by Django 2.1.2 on 2022-01-05 00:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0293_auto_20211216_1043"),
    ]

    operations = [
        migrations.CreateModel(
            name="S_Booking_Lines",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "e_type_of_packaging",
                    models.CharField(
                        blank=True,
                        max_length=36,
                        null=True,
                        verbose_name="Type Of Packaging",
                    ),
                ),
                (
                    "e_item_type",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Item Type"
                    ),
                ),
                (
                    "e_pallet_type",
                    models.CharField(
                        blank=True, max_length=24, null=True, verbose_name="Pallet Type"
                    ),
                ),
                (
                    "e_item",
                    models.CharField(
                        blank=True, max_length=56, null=True, verbose_name="Item"
                    ),
                ),
                ("e_qty", models.IntegerField(blank=True, null=True)),
                (
                    "e_weightUOM",
                    models.CharField(
                        blank=True, max_length=56, null=True, verbose_name="Weight UOM"
                    ),
                ),
                (
                    "e_weightPerEach",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight Per Each"
                    ),
                ),
                (
                    "e_dimUOM",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Dim UOM"
                    ),
                ),
                (
                    "e_dimLength",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Length"),
                ),
                (
                    "e_dimWidth",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Width"),
                ),
                (
                    "e_dimHeight",
                    models.FloatField(blank=True, null=True, verbose_name="Dim Height"),
                ),
                ("e_cubic", models.FloatField(blank=True, null=True)),
                ("e_cubic_2_mass_factor", models.FloatField(blank=True, null=True)),
                ("e_cubic_mass", models.FloatField(blank=True, null=True)),
                (
                    "fp_event_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fp_status",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "fp_message",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "z_createdAt",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                "db_table": "shared_booking_lines",
            },
        ),
        migrations.CreateModel(
            name="S_Bookings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "b_bookingID_Visual",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "b_dateBookedDate",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "v_FPBookingNumber",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "b_client_order_num",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "de_Deliver_By_Date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "b_client_name_sub",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "vx_freight_provider",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "v_service_Type_2",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "b_status",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=40,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "de_To_Address_Street_1",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "de_To_Address_Street_2",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "de_To_Address_State",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "de_To_Address_Suburb",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "de_To_Address_PostalCode",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "de_To_Address_Country",
                    models.CharField(
                        blank=True, default=None, max_length=12, null=True
                    ),
                ),
                (
                    "de_to_Contact_F_LName",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "de_Email",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "de_to_Phone_Mobile",
                    models.CharField(
                        blank=True, default=None, max_length=25, null=True
                    ),
                ),
                (
                    "de_to_Phone_Main",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "fp_event_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "fp_message",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "zoho_summary",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "zoho_event_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "booked_for_comm_communicate_via",
                    models.CharField(
                        blank=True, default=None, max_length=120, null=True
                    ),
                ),
                (
                    "z_createdAt",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                "db_table": "shared_bookings",
            },
        ),
        migrations.AddField(
            model_name="s_booking_lines",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.S_Bookings"
            ),
        ),
    ]
