# Generated by Django 2.1.2 on 2022-01-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0294_auto_20220105_0038"),
    ]

    operations = [
        migrations.RenameField(
            model_name="s_bookings",
            old_name="b_client_name_sub",
            new_name="b_client_name",
        ),
        migrations.RenameField(
            model_name="s_bookings",
            old_name="v_service_Type_2",
            new_name="vx_serviceName",
        ),
    ]
