# Generated by Django 2.1.2 on 2022-01-10 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0295_auto_20220105_0222"),
    ]

    operations = [
        migrations.AddField(
            model_name="s_booking_lines",
            name="z_updatedAt",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="s_bookings",
            name="z_updatedAt",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
