# Generated by Django 2.1.2 on 2022-01-20 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0299_auto_20220119_0612"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="b_promo_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name="Promotion Code",
            ),
        ),
    ]
