# Generated by Django 2.1.2 on 2022-01-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0300_auto_20220120_0159"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_093_b_promo_code",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
