# Generated by Django 2.1.2 on 2022-02-25 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0305_auto_20220224_0217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surcharge",
            name="quote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.API_booking_quotes",
            ),
        ),
    ]
