# Generated by Django 2.1.2 on 2022-03-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0306_auto_20220225_0129"),
    ]

    operations = [
        migrations.CreateModel(
            name="Linehaul",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "suburb_from",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "suburb_to",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("linehaul_booked_date", models.DateTimeField(null=True)),
                ("departure_date_planned", models.DateTimeField(null=True)),
                ("arrival_date_planned", models.DateTimeField(null=True)),
                ("arrival_date_actual", models.DateTimeField(null=True)),
                ("inv_linehaul_cost_ex_gst", models.FloatField(blank=True, null=True)),
                (
                    "guarantor",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("guaranteed_fill_percent", models.FloatField(blank=True, null=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "dme_linehauls",
            },
        ),
        migrations.CreateModel(
            name="LinehaulOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "dme_linehaul_orders",
            },
        ),
        migrations.AddField(
            model_name="fp_freight_providers",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="linehaulorder",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Bookings"
            ),
        ),
        migrations.AddField(
            model_name="linehaulorder",
            name="linehaul",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Linehaul"
            ),
        ),
        migrations.AddField(
            model_name="linehaulorder",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.API_booking_quotes"
            ),
        ),
    ]
