# Generated by Django 2.1.2 on 2022-03-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0307_auto_20220310_0455"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="selected",
            field=models.BooleanField(default=None, null=True),
        )
    ]
