# Generated by Django 2.1.2 on 2022-03-16 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0308_auto_20220314_2316"),
    ]

    operations = [
        migrations.AddField(
            model_name="linehaul",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="linehaul",
            name="paid_for_by",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
