# Generated by Django 2.1.2 on 2022-03-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0310_auto_20220317_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="linehaul",
            name="consignment_to_view",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="linehaul",
            name="constant_1",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="linehaul",
            name="fp_to_view",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
