# Generated by Django 2.1.2 on 2022-04-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0311_auto_20220329_0059"),
    ]

    operations = [
        migrations.AddField(
            model_name="linehaul",
            name="dme_linehaul_extra01",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="linehaul",
            name="dme_linehaul_extra02",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="linehaul",
            name="fp_invoice_id_to_set",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
