# Generated by Django 2.1.2 on 2022-04-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0312_auto_20220410_2333"),
    ]

    operations = [
        migrations.CreateModel(
            name="DME_Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "number",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                (
                    "suburb_from",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "suburb_to",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("linehaul_booked_date", models.DateTimeField(null=True)),
                ("departure_date_planned", models.TimeField(null=True)),
                ("arrival_date_planned", models.DateTimeField(null=True)),
                ("arrival_date_actual", models.DateTimeField(null=True)),
                ("inv_linehaul_cost_ex_gst", models.FloatField(blank=True, null=True)),
                (
                    "guarantor",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("guaranteed_fill_percent", models.FloatField(blank=True, null=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                ("active", models.BooleanField(default=None, null=True)),
                (
                    "paid_for_by",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("constant_1", models.BooleanField(default=None, null=True)),
                (
                    "fp_to_view",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "consignment_to_view",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "fp_invoice_id_to_set",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "dme_linehaul_extra01",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "dme_linehaul_extra02",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "z_createdByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Created by account",
                    ),
                ),
                (
                    "z_createdTimeStamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "z_modifiedByAccount",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Modified by account",
                    ),
                ),
                (
                    "z_modifiedTimeStamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "dme_vehicle",
            },
        ),
        migrations.AlterField(
            model_name="linehaulorder",
            name="linehaul",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.DME_Vehicle"
            ),
        ),
        migrations.DeleteModel(
            name="Linehaul",
        ),
    ]
