# Generated by Django 2.1.2 on 2022-04-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0313_auto_20220419_0534"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api_booking_quotes",
            name="s_05_LatestPickUpDateTimeFinal",
        ),
        migrations.RemoveField(
            model_name="api_booking_quotes",
            name="s_06_LatestDeliveryDateTimeFinal",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="s_05_LatestPickUpDateTimeFinal",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="s_06_LatestDeliveryDateTimeFinal",
        ),
    ]
