# Generated by Django 2.1.2 on 2022-04-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0314_auto_20220419_2329"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_freight_providers",
            name="last_vehicle_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
