# Generated by Django 2.1.2 on 2022-05-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0316_auto_20220426_2321"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surcharge",
            old_name="applied_at",
            new_name="booked_date",
        ),
        migrations.AddField(
            model_name="surcharge",
            name="actual_de_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="surcharge",
            name="actual_pu_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="surcharge",
            name="eta_de_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="surcharge",
            name="eta_pu_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
