# Generated by Django 2.1.2 on 2022-05-27 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0317_auto_20220511_2343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client_warehouses",
            name="type",
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="business_type",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="warehouse type"
            ),
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="instructions_linehual",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="main_warehouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dme_vehicle",
            name="planned_arrival",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="contact_name",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="client_warehouses",
            name="hours",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="fprouting",
            name="freight_provider",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Fp_freight_providers",
            ),
        ),
    ]
