# Generated by Django 2.1.2 on 2022-05-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0318_auto_20220527_0550"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_fp",
            name="fuel_levy",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
