# Generated by Django 2.1.2 on 2022-06-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0319_auto_20220530_0201"),
    ]

    operations = [
        migrations.AddField(
            model_name="s_bookings",
            name="b_booking_Priority",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
