# Generated by Django 2.1.2 on 2022-06-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0320_auto_20220602_0051"),
    ]

    operations = [
        migrations.AddField(
            model_name="s_bookings",
            name="s_06_Latest_Delivery_Date_Time_Override",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
