# Generated by Django 2.1.2 on 2022-07-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0322_auto_20220627_0243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="v_vehicle_Type",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="Vehicle Type",
            ),
        ),
    ]
