# Generated by Django 2.1.2 on 2022-07-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0323_auto_20220714_0101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_1_headers",
            name="b_clientPU_Warehouse",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="warehouse"
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="b_clientPU_Warehouse",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name="warehouse",
            ),
        ),
    ]
