# Generated by Django 2.1.2 on 2022-07-27 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0324_auto_20220726_0418"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="dme_client_notes",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
