# Generated by Django 2.1.2 on 2022-08-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0325_auto_20220727_0113"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking_lines",
            name="e_util_cbm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Utilised Cubic Meter"
            ),
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="e_util_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Utilised Height"
            ),
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="e_util_kg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Utilised Cubic KG"
            ),
        ),
    ]
