# Generated by Django 2.1.2 on 2022-08-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0326_auto_20220805_0558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_employees",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
