# Generated by Django 2.1.2 on 2022-08-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0327_auto_20220815_2338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api_booking_quotes",
            name="tax_id_4",
        ),
        migrations.RemoveField(
            model_name="api_booking_quotes",
            name="tax_value_4",
        ),
        migrations.AddField(
            model_name="api_booking_quotes",
            name="lowest_quote_flag",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
