# Generated by Django 2.1.2 on 2022-08-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0328_auto_20220819_0142"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_warehouses",
            name="connote_number",
            field=models.IntegerField(default=0),
        ),
    ]
