# Generated by Django 2.1.2 on 2022-09-01 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0329_auto_20220826_0234"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_094_client_sales_total",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="client_sales_total",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
