# Generated by Django 2.1.2 on 2022-09-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0330_auto_20220901_0338"),
    ]

    operations = [
        migrations.AddField(
            model_name="fp_freight_providers",
            name="last_atl_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
