# Generated by Django 2.1.2 on 2022-09-08 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0331_auto_20220906_2308"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="fp_atl_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
