# Generated by Django 2.1.2 on 2022-10-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0332_auto_20220908_0105"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_092_is_quote_locked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="is_quote_locked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
