# Generated by Django 2.1.2 on 2022-10-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0333_auto_20221012_1446"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="v_service_Delivery_Days_Percentage_Days_TO_PU",
        ),
        migrations.AddField(
            model_name="bookings",
            name="v_project_percentage",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
