# Generated by Django 2.1.2 on 2022-11-21 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0335_auto_20221107_0545"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_vehicle",
            name="constant_2",
            field=models.IntegerField(default=2),
        ),
    ]
