# Generated by Django 2.1.2 on 2022-12-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0338_auto_20221227_0633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dme_clients",
            name="status_email",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="dme_clients",
            name="status_phone",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="dme_clients",
            name="status_send_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
