# Generated by Django 2.1.2 on 2023-01-25 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0339_auto_20221228_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='opt_authority_to_leave',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
