# Generated by Django 2.1.2 on 2023-02-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0340_auto_20230125_0250"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_confirmation_lines",
            name="barcode_data",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="api_booking_confirmation_lines",
            name="barcode_scanned_by",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="api_booking_confirmation_lines",
            name="barcode_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
