# Generated by Django 2.1.2 on 2023-04-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0342_auto_20230223_0023"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_quotes",
            name="is_from_api",
            field=models.BooleanField(default=False),
        ),
    ]
