# Generated by Django 2.1.2 on 2023-05-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0342_auto_20230223_0023"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_096_v_customer_code",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
