# Generated by Django 2.1.2 on 2023-06-08 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0343_auto_20230522_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_2_lines",
            name="b_097_e_bin_number",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="e_bin_number",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
