# Generated by Django 2.1.2 on 2023-06-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0343_auto_20230522_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_fp",
            name="connote_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
