# Generated by Django 2.1.2 on 2023-06-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0344_auto_20230608_0013'),
        ('api', '0343_auto_20230417_0227'),
    ]

    operations = [
    ]
