# Generated by Django 2.1.2 on 2023-07-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0345_merge_20230622_0106'),
        ('api', '0344_auto_20230605_2316'),
    ]

    operations = [
    ]
