# Generated by Django 2.1.2 on 2023-07-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0346_merge_20230703_0044"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_fp",
            name="sscc_seq",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="fp_status_history",
            name="driver",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fp_status_history",
            name="location",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
