# Generated by Django 2.1.2 on 2023-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0347_auto_20230703_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_lines',
            name='warranty_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='warranty_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="booking_lines",
            name="note",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
