# Generated by Django 2.1.2 on 2023-07-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0348_auto_20230713_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_2_lines",
            name="e_item_type",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Item Type"
            ),
        ),
        migrations.AlterField(
            model_name="bok_2_lines",
            name="l_003_item",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Item"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="e_item",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Item"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="sscc",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
