# Generated by Django 2.1.2 on 2023-07-20 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0348_auto_20230713_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='DME_Voice_Calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField(blank=True, null=True, verbose_name='Booking ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('last_call_timestamp', models.DateTimeField(auto_now=True, null=False, verbose_name='Last Call Timestamp')),
                ('call_count', models.IntegerField(default=0, verbose_name='Call Count')),
                ('is_client_received', models.BooleanField(default=False, verbose_name='If client received or not')),
            ],
            options={
                'db_table': 'dme_voice_calls',
            },
        ),
    ]
