# Generated by Django 2.1.2 on 2023-07-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0349_auto_20230721_0210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bok_2_lines",
            name="l_003_item",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Item"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="e_item",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Item"
            ),
        ),
        migrations.AlterField(
            model_name="booking_lines",
            name="note",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
