# Generated by Django 2.1.2 on 2023-07-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0350_auto_20230727_0210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s_booking_lines",
            name="e_item",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Item"
            ),
        ),
    ]
