# Generated by Django 2.1.2 on 2023-08-07 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0351_auto_20230731_2311"),
    ]

    operations = [
        migrations.AddField(
            model_name="client_warehouses",
            name="tge_ipec_connote_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="tge_ipec_connote_prefix",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="tge_pe_sscc_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client_warehouses",
            name="tge_pe_sscc_prefix",
            field=models.IntegerField(default=0),
        ),
    ]
