# Generated by Django 2.1.2 on 2023-08-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0352_auto_20230807_0009"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client_warehouses",
            old_name="tge_ipec_connote_prefix",
            new_name="tge_ipec_sscc_index",
        ),
        migrations.RenameField(
            model_name="client_warehouses",
            old_name="tge_pe_sscc_prefix",
            new_name="tge_pe_connote_index",
        ),
    ]
