# Generated by Django 2.1.2 on 2023-09-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0353_auto_20230807_0136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fprouting",
            name="routing_group",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
