# Generated by Django 2.1.2 on 2023-09-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0354_auto_20230911_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_manifest_log",
            name="booking_ids",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="dme_manifest_log",
            name="freight_provider",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
