# Generated by Django 2.1.2 on 2023-09-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0355_auto_20230917_0157"),
    ]

    operations = [
        migrations.AddField(
            model_name="dme_manifest_log",
            name="note",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
