# Generated by Django 2.1.2 on 2023-09-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0356_auto_20230917_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_attachments',
            name='is_hidden',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='is_hidden'),
        ),
        migrations.AlterField(
            model_name='bok_1_headers',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='api_booking_quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='client_overrided_quote',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fc_log',
            name='new_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='fc_log',
            name='old_quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='linehaulorder',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.API_booking_quotes'),
        ),
    ]
