# Generated by Django 2.1.2 on 2023-10-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0357_auto_20230926_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_attachments',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desc'),
        ),
    ]
