# Generated by Django 2.1.2 on 2023-11-13 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0358_auto_20231003_0828"),
    ]

    operations = [
        migrations.AddField(
            model_name="s_bookings",
            name="b_client_name_sub",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
