# Generated by Django 2.1.2 on 2023-11-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0360_auto_20231115_0506"),
    ]

    operations = [
        migrations.AddField(
            model_name="api_booking_confirmation_lines",
            name="fm_date_text",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
