# Generated by Django 2.1.2 on 2024-01-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0361_auto_20231115_0514"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "b_bookingID_Visual",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="BookingID Visual",
                    ),
                ),
                (
                    "imported_from_xls",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("allocation_dollar_amount", models.FloatField(blank=True, null=True)),
                (
                    "dme_invoice_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fk_booking_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "fk_import_file_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "imported_from_xls",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("si_01_fp", models.CharField(blank=True, max_length=32, null=True)),
                ("si_03_fp_booking_date", models.DateField(blank=True, null=True)),
                (
                    "si_04_5fp_invoice_num",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "si_50_1_dme_invoice_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "si_17_02_fpchargefinal_2_00",
                    models.FloatField(blank=True, null=True),
                ),
                ("si_17_8_fpfuellevy", models.FloatField(blank=True, null=True)),
                (
                    "fk_dmevisual_id_final",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
            ],
            options={
                "db_table": "supinv_supplierinvoice",
            },
        ),
    ]
