# Generated by Django 2.1.2 on 2024-02-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0364_auto_20240214_0413"),
    ]

    operations = [
        migrations.AddField(
            model_name="bok_1_headers",
            name="b_097_bid_closing_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="bid_closing_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
