# Generated by Django 2.1.2 on 2024-02-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0365_auto_20240214_0905"),
    ]

    operations = [
        migrations.CreateModel(
            name="SHIP_SSCC_Ranges",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_type",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "source_system_code",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "prefix_1",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "prefix_2",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    "ship_start",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "ship_current",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("ship_end", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "sscc_start",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "sscc_current",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("sscc_end", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created Timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified Timestamp"
                    ),
                ),
                (
                    "freight_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Fp_freight_providers",
                    ),
                ),
            ],
            options={
                "db_table": "ship_sscc_ranges",
            },
        ),
    ]
