# Generated by Django 2.1.2 on 2024-02-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0365_auto_20240214_0905"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="num_01",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="num_02",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="num_03",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="text_01",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="text_02",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="text_03",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="num_01",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="num_02",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="num_03",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="text_01",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="text_02",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="text_03",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
