# Generated by Django 2.1.2 on 2024-02-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0366_auto_20240226_0518"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="b_client_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=36,
                null=True,
                verbose_name="Client Name",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="b_client_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=36,
                null=True,
                verbose_name="Client Name",
            ),
        ),
    ]
