# Generated by Django 2.1.2 on 2024-02-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0370_auto_20240229_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='fp_inv_total_mass_kg',
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='fpinv_total_mass_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='fpinv_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
