# Generated by Django 2.1.2 on 2024-02-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0371_auto_20240301_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='cost_to_add_to_fp_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='cost_to_show_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='pk_idinvoicedata',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='si_18_5markupfinal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
