# Generated by Django 2.1.2 on 2024-03-01 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0372_auto_20240301_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpinv_order_totals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pk_fm', models.CharField(blank=True, max_length=64, null=True)),
                ('fk_booking_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='FK Booking Id')),
                ('dme_number', models.IntegerField(blank=True, null=True)),
                ('fpinv_total_mass_kg', models.FloatField(blank=True, null=True)),
                ('fpinv_total_cbm', models.FloatField(blank=True, null=True)),
                ('fpinv_factor', models.FloatField(blank=True, null=True)),
                ('fpinv_total_cbm_kg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fpinv_order_totals',
            },
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='fpinv_factor',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='fpinv_total_cbm',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='fpinv_total_cbm_kg',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='fpinv_total_mass_kg',
        ),
    ]
