# Generated by Django 2.1.2 on 2024-03-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0372_auto_20240301_0702"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="fpinv_factor_fp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
