# Generated by Django 2.1.2 on 2024-03-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0373_auto_20240301_1227'),
        ('api', '0373_auto_20240303_0040'),
    ]

    operations = [
    ]
