# Generated by Django 2.1.2 on 2024-03-06 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0375_auto_20240304_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dme_tokens",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
