# Generated by Django 2.1.2 on 2024-03-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0376_auto_20240306_2246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="b_ImportedFromFile",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Imported File Filed",
            ),
        ),
    ]
