# Generated by Django 2.1.2 on 2024-03-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0377_auto_20240312_0255'),
        ('api', '0366_auto_20240226_0401'),
    ]

    operations = [
    ]
