# Generated by Django 2.1.2 on 2024-03-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0349_auto_20230720_1015'),
        ('api', '0378_merge_20240313_1259'),
    ]

    operations = [
    ]
