# Generated by Django 2.1.2 on 2024-03-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0379_merge_20240318_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierinvoice',
            old_name='num_02',
            new_name='fpinv_factor',
        ),
        migrations.RenameField(
            model_name='supplierinvoice',
            old_name='num_03',
            new_name='fpinv_total_cbm',
        ),
    ]
