# Generated by Django 2.1.2 on 2024-05-08 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0380_auto_20240320_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='is_flagged_no_show_bi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='total_cost_show_client',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
