# Generated by Django 2.1.2 on 2024-06-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0381_auto_20240508_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok_1_headers',
            name='b_098_pallet_loscam_account',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bok_2_lines',
            name='b_098_pallet_loscam_account',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='booking_lines',
            name='b_pallet_loscam_account',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='b_pallet_loscam_account',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
