SURCHARGE_NAME_DESC = {
    "DELIVER-ME": {
        "Pallet 1.2W * 1.2L or less (SYD - MEL)": "Deliver-ME Direct (Into Premises) SYD - MEL",
        "Up to Pallet 1.2W * 1.6L (SYD - MEL)": "Deliver-ME Direct (Into Premises) SYD - MEL",
        "Up to Pallet 1.2W * 1.6L (SYD - MEL)": "Deliver-ME Direct (Into Premises) SYD - MEL",
        "Pallet 1.2W * 1.2L or less (SYD - BRIS)": "Deliver-ME Direct (Into Premises) SYD - BRIS",
        "Up to Pallet 1.2W * 1.6L (SYD - BRIS)": "Deliver-ME Direct (Into Premises) SYD - BRIS",
        "Up to Pallet 1.2W * 1.6L (SYD - BRIS)": "Deliver-ME Direct (Into Premises) SYD - BRIS",
        "Pallet 1.2W * 1.2L or less (SYD - ADE)": "Deliver-ME Direct (Into Premises) SYD - ADE",
        "Up to Pallet 1.2W * 1.6L (SYD - ADE)": "Deliver-ME Direct (Into Premises) SYD - ADE",
        "Up to Pallet 1.2W * 1.6L (SYD - ADE)": "Deliver-ME Direct (Into Premises) SYD - ADE",
        "Non Pallet CBM (SYD - MEL)": "Deliver-ME Direct (Into Premises) SYD - MEL",
        "Non Pallet CBM (SYD - BRIS)": "Deliver-ME Direct (Into Premises) SYD - BRIS",
        "Non Pallet CBM (SYD - ADE)": "Deliver-ME Direct (Into Premises) SYD - ADE",
        "PU tail lift man (Pickup)": "Additional Service fee for 2 man",
        "DE tail lift man (Delivery)": "Additional Service fee for 2 man",
    },
    "ALLIED": {
        "Lengths [LSC] 1.20-2.39 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 2.40-3.59 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 3.60-4.19 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 4.20-4.79 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] 4.80-5.99 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Lengths [LSC] over 6 metre": "Items that exceed lenghts in any direction will attract a surcharge",
        "Width [WS] 1.10-1.60 metre": "Items that exceed widthwill attract a surcharge",
        "Width [WS] 1.61-2.4 metre": "Items that exceed widthwill attract a surcharge",
        "Tail Lift [TL]": "For deliveries requiring tail lifts",
        "Oversize Pallets": "Standard pallet sizes are measured at a maximum of 1.2m x 1.2m x 1.4m and weighed at a maximum of 500 kilograms. Pallets greater than will incur oversize pallet charges, in line with the number of pallet spaces occupied, charged in full pallets. An additional pallet charge will apply.",
        "Minimum Charge-Skids/ Pallets": "The minimum charge for a skid is 175 kilograms, and for a pallet is 350 kilograms.  Please note that even if your freight is not presented on a pallet or skid, these charges may be applied if items cannot be lifted by one person.",
        "HD": "FREIGHT OVERSIZED HOME DELIVERY",
        "LSC": "LENGTH SURCHARGE",
        "MHF": "MANUAL HANDLING FEE",
        "Onforwarding(Pickup)": "All our rates apply from pick up and to drop, where a delivery made to a nominated regional, country or remote location, as outlined on our Onforwarding matrix, an onforwarding surcharge is applicable.  Please contact Allied Express for a copy of this matrix.",
        "Onforwarding(Delivery)": "All our rates apply from pick up and to drop, where a delivery made to a nominated regional, country or remote location, as outlined on our Onforwarding matrix, an onforwarding surcharge is applicable.  Please contact Allied Express for a copy of this matrix.",
        "Overweight": "Base charge plus kilo charge",
        "Home Deliveries [HD]": "FREIGHT OVERSIZED HOME DELIVERY",
        "Home Deliveries [HD] - 22": "The Home delivery fee’s would be 50% less than what is shown, so we know it is not the standard price. For freight being delivered to residential addresses a surcharge per consignment less than 23 kgs (dead or cubic weight)",
        "Home Deliveries [HD] - 55": "The Home delivery fee’s would be 50% less than what is shown, so we know it is not the standard price. For freight being delivered to residential addresses a surcharge per consignment between 23 and 55 kgs (dead or cubic weight)",
        "Home Deliveries [HD] - 90": "The Home delivery fee’s would be 50% less than what is shown, so we know it is not the standard price. For freight being delivered to residential addresses a surcharge per consignment between 55 and 90 kgs (dead or cubic weight)",
        "Home Deliveries [HD] - 136": "The Home delivery fee’s would be 50% less than what is shown, so we know it is not the standard price. For freight being delivered to residential addresses a surcharge per consignment between 90 and 136 kgs (dead or cubic weight)",
    },
    "HUNTER": {
        "Excess Lengths: 1.5m up to/not incl. 2.5m": "",
        "Excess Lengths: 2.5m up to/not incl. 4.0m": "",
        "Excess Lengths: 4m up to/not incl. 6.0m": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 34-49kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 50-74kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 75-99kg": "",
        "Bulk Delivery to Residential Address - Average dead or cubic weight per item 100kg or greater": "",
        "Tail-Lift Truck8(pickup)": "",
        "Tail-Lift Truck8(delivery)": "",
    },
    "TNT": {
        "Dangerous Goods (Road Express)": "Surcharge per consignment. In addition, the MHP Fee will apply per item to each and all items consigned under the same consignment note where that consignment contains Dangerous Goods, including any non-Dangerous Goods items consigned under that consignment note. (Dangerous Goods consignment notes are to contain Dangerous Goods items only.)",
        "Dangerous Goods (excluding Road Express)": "Surcharge per consignment. In addition, the MHP Fee will apply per item to each and all items consigned under the same consignment note where that consignment contains Dangerous Goods, including any non-Dangerous Goods items consigned under that consignment note. (Dangerous Goods consignment notes are to contain Dangerous Goods items only.)",
        "Residential Pickup (RSP)": "Fee per consignment for pick up from a residential address4.",
        "Heavyweight Residential Pickup (RSP30)": "Fee per consignment for pick up from a residential address4 with a chargeable weight5 of 30kg and over, but less than 100kg.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Heavyweight Residential Pickup (RSP100)": "Fee per consignment for pick up from a residential address4 with a chargeable weight5 of 100kg and over.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Residential Delivery (RSD)": "Fee per consignment for delivery to a residential address4.",
        "Heavyweight Residential Delivery (RSD30)": "Fee per consignment for delivery from a residential address4 with a chargeable weight5 of 30kg and over, but less than 100kg. 6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4.",
        "Heavyweight Residential Delivery (RSD100)": "Fee per consignment for delivery from a residential address4 with a chargeable weight5 of 100kg and over.6 This fee will be applied in addition to any other fee or surcharge in relation to the consignment, including the existing Residential Delivery Fee (RSD) and/or Residential Pickup Fee (RSP) of $5 per consignment for delivery to and/or pickup from a residential address4. 4 ’Residential address’ means a home or private residence, including locations where a business is operated from the home or private residence, and/or a shipment in which the shipper has designated the delivery/pickup address as residential. 5 This fee will be applied to each consignment’s chargeable weight, which is the greater of the dead weight and the cubic weight, calculated in accordance with the TNT Australia Pty Limited Terms and Conditions of Carriage and other services. 6 Weight limitations will be subject to TNT’s health and safety guidelines and/or operation constraints.",
        "Oversize Freight (OS0)": "Oversize freight where any one dimension (length, height or width) exceeds 1.49 metres.",
        "Oversize Freight (OS1)": "Oversize freight where any one dimension (length, height or width) exceeds 1.99 metres.",
        "Oversize Freight (OS2)": "Oversize freight where any one dimension (length, height or width) exceeds 2.99 metres.",
        "Oversize Freight (OS3)": "Oversize freight where any one dimension (length, height or width) exceeds 3.99 metres.",
        "Oversize Freight (OS4)": "Oversize freight where any one dimension (length, height or width) exceeds 4.99 metres.",
        "Oversize Freight (OS5)": "Oversize freight where any one dimension (length, height or width) exceeds 5.99 metres.",
        "Manual Handling Processing (MHP) Fee": "From 7 December 2020, MHP Fee3 will be $12.50 per item on items which are not compatible with TNT's sortation system and require manual handling due to size1, weight2, fragility (including glass), poor packaging (including where the parcel is unstable due to poor weight distribution) and/or unusual shape (including tubes, flat pack items) and Dangerous Goods. 1 Length <200mm or >1200mm and/or Width <100mm or >600mm and/or Height <15mm or >800mm and/or Diagonal Length >1200mm 2 Weight <250g or >30kg 3 The MHP fee is charged per item in addition to any other applicable surcharge for the consignment, including oversize surcharge and Dangerous Goods' surcharge. The MHP Fee is applied to each and all items under a consignment note, which contains Dangerous Goods (Dangerous Goods consignment notes are to contain Dangerous Goods items only).",
    },
    "CAMERONS": {
        "Tail-Gate(pickup)": "Applied when there is tail lift pickup. If service is express, then 110% is applied",
        "Tail-Gate(delivery)": "Applied when there is tail lift delivery. If service is express, then 110% is applied",
    },
    "NORTHLINE": {
        "Account Service Fee": "Charged by account per trading week",
        "Additional Labour": "Any pickup and/or delivery requiring an extra person",
        "Dangerous Goods": "Goods identified/declarable under the Commonwealth, states and territories. Explosives Regulations and the Australian Dangerous Goods Code.",
        "Express Transit": "The fee applies where Pickup and/or delivery to a time window where the transit is 1 or more days inside the published general transit schedule. All requests are required to be approved with a Sales Representative prior to booking.",
        "Futile Deliver/Pickup": "Where a vehicle is dispatched, and the goods are unable to be either picked up or delivered",
        "Hand Load/Unloda": "Goods with a maximum item weight of 25 kilograms which require hand loading or offloading. Multiple consignments booked on the same job will have the time calculated on the total job. Charges will be calculated in 15-minute increments from time of arrival onsite.",
        "Hazardous Goods Transport": "Goods transported as Hazardous or Waste product, declarable under the Environmental Protection Act.",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Lost Pallets": "Lost or outstanding Chep/Loscam pallets.",
        "Manual Connote": "A manual connote fee may be charged where a manual connote is completed by the Customer (or on the Customer’s behalf) which must then be manually entered into the Northline’s IT system. This fee does not apply to consignment notes electronically supplied to the Customer by Northline (generated by Northline’s IT systems) or electronically manifested by the Customer and/or transferred to Northline’s IT server on or before the day of despatch.",
        "Over-length Goods": "Where the length of the consignment matches the following dimensions.",
        "Oversize Pallets/Un-Packed Goods": "Oversized and/or unpacked goods that have been accepted by Northline will be charged by the equivalent pallet space/s area taken up on the load. Measurements will be taken to the trailer height and width and not the product height and width.",
        "Redirection Fee/Incorrect Address": "It is the responsibility of the Customer to provide the correct pickup and delivery address. Where an incorrect address is supplied a re-direction fee will be applicable to have the consignment re-delivered. This applies when redirected whilst in transit or when futile delivery has occurred, and the redelivery is to a new destination.",
        "Regionals and Remote Locations": "Regional pricing is to the nominated township area and immediate surrounds only (it does not refer to the area governed i.e. shire or city of). Whilst every effort is made to provide accurate pricing, on occasion Northline may be charged “extra” by our Agents for locations outside of this area or for difficult to access sites. When this occurs, Northline reserves the right to charge an additional fee or the Receiver may be given the option of collecting the freight from the Agent’s depot.",
        "Remote Sites, Islands, Barge or Ferry Services": "Goods to these sites may incur additional charges. Please discuss these with a Sales Representative prior to booking.",
        "Reporting: Standard": "Regular Automated Standard Reporting: -Stock Received – Weekly Reports showing daily activity of Stock Received into the warehouse -Stock Despatched – Weekly Reports showing daily activity of Stock Despatched from the warehouse -Stock on Hand – Total Number of Outers/pallets in storage at the end of each day/week.",
        "Reporting: Non-Standard": "Where Northline are required to provide non-standard or tailored performance reports, a format will be agreed on before the customer will be charged for this service.",
        "Short Term Holding/Warehousing": "The development of any non-standard or tailored reports at the request of a Customer. Goods which have been negotiated to be held or where the delivery cannot be performed within 4 days.",
        "Specialized Lifting or Pickup/Delivery": "Rates do not include specialised vehicle requirements such as Hiabs or Crane vehicles. The cost for the use of these specialised vehicles will be priced on application.",
        "Storage and Handling": "Specific to Warehousing Customers. Goods will be stored and warehoused in a manner that is safe, proper and fit for purpose. Goods to be despatched will be assembled in a manner that ensures no damage occurs to the goods during transport. Documentation will also be sent with the despatched orders. Northline’s warehousing services will include the following activities: -Receiving into store as per agreed timeframes -Order picking, processing and despatching as per agreed timeframes -Confirming orders directly from WMS and checking prior to despatch -All orders are generated with industry serial shipping container code and address labels -Unloading all imported or domestic goods -Storing all goods whilst ensuring FIFO or FEFO, as directed by customer -Completing Cycle counts/stocktakes as required by customer -Ensuring efficient WMS interface with controls in place for systems/figures integrity",
        "Tailgate": "Pickups and/or deliveries requiring the use of a Tailgate vehicle.",
        "Top Load Only": "Freight designated as “top load only” may attract a charge equivalent to the full pallet height of the trailer.",
        "Waiting Time": "Charge applies where allocated loading and/or unloading time is exceeded and will be calculated in 15-minute increments.",
        "Wharf Terminal": "Timeslot booking fees and infrastructure fees charged by wharf terminal providers for containers picked up or dropped off at the wharf will be passed onto the Customer.",
    },
    "NORTHLINE": {
        "Account Service Fee": "Charged by account per trading week",
        "Additional Labour": "Any pickup and/or delivery requiring an extra person",
        "Dangerous Goods": "Goods identified/declarable under the Commonwealth, states and territories. Explosives Regulations and the Australian Dangerous Goods Code.",
        "Express Transit": "The fee applies where Pickup and/or delivery to a time window where the transit is 1 or more days inside the published general transit schedule. All requests are required to be approved with a Sales Representative prior to booking.",
        "Futile Deliver/Pickup": "Where a vehicle is dispatched, and the goods are unable to be either picked up or delivered",
        "Hand Load/Unloda": "Goods with a maximum item weight of 25 kilograms which require hand loading or offloading. Multiple consignments booked on the same job will have the time calculated on the total job. Charges will be calculated in 15-minute increments from time of arrival onsite.",
        "Hazardous Goods Transport": "Goods transported as Hazardous or Waste product, declarable under the Environmental Protection Act.",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Lost Pallets": "Lost or outstanding Chep/Loscam pallets.",
        "Manual Connote": "A manual connote fee may be charged where a manual connote is completed by the Customer (or on the Customer’s behalf) which must then be manually entered into the Northline’s IT system. This fee does not apply to consignment notes electronically supplied to the Customer by Northline (generated by Northline’s IT systems) or electronically manifested by the Customer and/or transferred to Northline’s IT server on or before the day of despatch.",
        "Over-length Goods": "Where the length of the consignment matches the following dimensions.",
        "Oversize Pallets/Un-Packed Goods": "Oversized and/or unpacked goods that have been accepted by Northline will be charged by the equivalent pallet space/s area taken up on the load. Measurements will be taken to the trailer height and width and not the product height and width.",
        "Redirection Fee/Incorrect Address": "It is the responsibility of the Customer to provide the correct pickup and delivery address. Where an incorrect address is supplied a re-direction fee will be applicable to have the consignment re-delivered. This applies when redirected whilst in transit or when futile delivery has occurred, and the redelivery is to a new destination.",
        "Regionals and Remote Locations": "Regional pricing is to the nominated township area and immediate surrounds only (it does not refer to the area governed i.e. shire or city of). Whilst every effort is made to provide accurate pricing, on occasion Northline may be charged “extra” by our Agents for locations outside of this area or for difficult to access sites. When this occurs, Northline reserves the right to charge an additional fee or the Receiver may be given the option of collecting the freight from the Agent’s depot.",
        "Remote Sites, Islands, Barge or Ferry Services": "Goods to these sites may incur additional charges. Please discuss these with a Sales Representative prior to booking.",
        "Reporting: Standard": "Regular Automated Standard Reporting: -Stock Received – Weekly Reports showing daily activity of Stock Received into the warehouse -Stock Despatched – Weekly Reports showing daily activity of Stock Despatched from the warehouse -Stock on Hand – Total Number of Outers/pallets in storage at the end of each day/week.",
        "Reporting: Non-Standard": "Where Northline are required to provide non-standard or tailored performance reports, a format will be agreed on before the customer will be charged for this service.",
        "Short Term Holding/Warehousing": "The development of any non-standard or tailored reports at the request of a Customer. Goods which have been negotiated to be held or where the delivery cannot be performed within 4 days.",
        "Specialized Lifting or Pickup/Delivery": "Rates do not include specialised vehicle requirements such as Hiabs or Crane vehicles. The cost for the use of these specialised vehicles will be priced on application.",
        "Storage and Handling": "Specific to Warehousing Customers. Goods will be stored and warehoused in a manner that is safe, proper and fit for purpose. Goods to be despatched will be assembled in a manner that ensures no damage occurs to the goods during transport. Documentation will also be sent with the despatched orders. Northline’s warehousing services will include the following activities: -Receiving into store as per agreed timeframes -Order picking, processing and despatching as per agreed timeframes -Confirming orders directly from WMS and checking prior to despatch -All orders are generated with industry serial shipping container code and address labels -Unloading all imported or domestic goods -Storing all goods whilst ensuring FIFO or FEFO, as directed by customer -Completing Cycle counts/stocktakes as required by customer -Ensuring efficient WMS interface with controls in place for systems/figures integrity",
        "Tailgate": "Pickups and/or deliveries requiring the use of a Tailgate vehicle.",
        "Top Load Only": "Freight designated as “top load only” may attract a charge equivalent to the full pallet height of the trailer.",
        "Waiting Time": "Charge applies where allocated loading and/or unloading time is exceeded and will be calculated in 15-minute increments.",
        "Wharf Terminal": "Timeslot booking fees and infrastructure fees charged by wharf terminal providers for containers picked up or dropped off at the wharf will be passed onto the Customer.",
    },
    "HI-TRANS": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Manual Connote": "Automatically charged based on entry method",
        "Over-length Freight - plus GST Capital Lanes": "Where the length of the consignment matches the following dimensions.",
    },
    "BLACKS": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "25% surcharge ontop of the freight rate",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Manual Connote": "Automatically charged based on entry method",
        "Over-length Freight - plus GST Capital Lanes": "Where the length of the consignment matches the following dimensions.",
    },
    "BLENNER": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "Dangerous Goods consignments incurr a 25% surcharge ontop of the freight rate + $15 Basic Charge",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Tailgate": "Pickups and/or deliveries requiring the use of a Tailgate vehicle.",
        "Manual Connote": "Automatically charged based on entry method",
        "Over-length Freight - plus GST Capital Lanes": "Where the length of the consignment matches the following dimensions.",
    },
    "BLUESTAR": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Manual Connote": "Automatically charged based on entry method",
        "Over size surcharges": "Over Dimensional freight (>2.4M length) may incur additional transit time.",
    },
    "VFS": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Manual Connote": "Automatically charged based on entry method",
        "Over size surcharges": "Over Dimensional freight (>2.4M length) may incur additional transit time.",
    },
    "TOLL": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Tail Lift Requirement": "When a consignment involving pallets or other heavy consignments requires the use of a tail lift or tilt tray truck.",
        "Over-length Goodss": "Where the length of the consignment matches the following dimensions.",
    },
    "DXT": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Dead Weight": "Base charge plus kilo charge",
        "Oversize Charge": "",
    },
    "FOLLOWMONT": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Dead Weight": "Base charge plus kilo charge",
        "Oversize Charge": "",
    },
    "SADLIERS": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Dead Weight": "Base charge plus kilo charge",
        "Oversize Charge": "",
    },
    "AFS": {
        "Additional Labour": "Consignments requiring additional labour for services may incur Ad-hoc charges",
        "Dangerous Goods": "",
        "Hand Load/Unloda": "",
        "Home Delivery/Residential": "Pickups and/or deliveries to private addresses. Hand load/unload, tailgate and waiting time fees may also apply where applicable.",
        "Dead Weight": "Base charge plus kilo charge",
        "Oversize Charge": "",
    },
    "DIRECT FREIGHT": {
        "Destination Surcharge": "Surcharge for specific destination.",
        "TAILGATE PICKUP": "TAILGATE PICKUP",
        "TAILGATE DELIVERY": "TAILGATE DELIVERY",
    },
}
